USE [kikker]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIKKER_T_11_PRECIOS_BKP]    Script Date: 19/06/2025 15:49:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_KIKKER_T_11_PRECIOS_BKP]
AS
/*
COD_REGIONAL - Nome do grupo econômico (não obrigatório)
COD_FORNECEDOR - Código do Fornecedor
COD_LOJA - Código da Loja (não obrigatório)
COD_PRODUTO - Código do Produto
QT_UN_COMPRA - Quantidade de produtos em unidade de venda na embalagem de compra
UN_COMPRA - Unidade de compra. (Ex: CX, UN, M,KG)
PRECO_UNITARIO - Preço unitário em unidade de venda
VALIDADE - Se o preço for válido até determinada data informar a data (formato AAAA-MM-DD)
PRECO_UNIT_SEM_IMPOSTO	Precio Unitario en unidades de compra sin impuestos	N
PRAZO_ENTREGA	Plazo de Entrega	S
PRINCIPAL	Verdadero o falso (si es el proveedor principal de la clave de la tienda del producto)	S
COD_CONTRATO	Código de contrato	N
PRAZO_PAGAMENTO	Plazo en dias	N
PESO	pedo producto unidades de compra	N
VOLUMEN	Pedo producto unidades de compra	N
N_CAMADAS_PALETE	Número de camadas	N
QTD_PRODUTOS_CAMADAS_PALETE	Número de productos en unidades de venta por camadas	N

agregado 6/09/2023 a pedido de Kikker Brasil

COD_REGIONAL, COD_FORNECEDOR, COD_LOJA, COD_PRODUTO, QT_UN_COMPRA, UN_COMPRA, PRECO_UNITARIO; VALIDADE;PRECO_UNIT_SEM_IMPOSTO;PRAZO_ENTREGA; PRINCIPAL; COD_CONTRATO;PRAZO_PAGAMENTO; PESO; VOLUME;N_CAMADAS_PALETE;QTD_PRODUTOS_CAMADAS_PALETE, COD_GRUPO_LOJA, COD_GRUPO_FORNECEDOR, SELL_IN

COD_CONTRATO  - (OPCIONAL) Código do Contrato
PRAZO_PAGAMENTO - (OPCIONAL) Prazo de pagamento em dias
PESO - (OPCIONAL) Peso do produto em unidade de compra - Não obrigatório, enviar nulo
VOLUME - (OPCIONAL) Peso do produto em unidade de compra - Não obrigatório, enviar nulo
N_CAMADAS_PALETE - (OPCIONAL) Número de camadas  - Não obrigatório, enviar nulo
QTD_PRODUTOS_CAMADAS_PALETE - (OPCIONAL) Número produto em unidade de venda por camadas  - Não obrigatório, enviar nulo
COD_GRUPO_LOJA -  (NÃO OBRIGATÓRIO) Código do grupo de loja.
COD_GRUPO_FORNECEDOR -  (NÃO OBRIGATÓRIO) Código do grupo de fornecedor.
SELL_IN  -  (NÃO OBRIGATÓRIO) Informação de SELL IN.

*/

BEGIN
SET NOCOUNT ON;
	SELECT 'COD_REGIONAL','COD_FORNECEDOR','COD_LOJA','COD_PRODUTO','QT_UN_COMPRA','UN_COMPRA','PRECO_UNITARIO','VALIDADE','PRECO_UNIT_SEM_IMPOSTO','PRAZO_ENTREGA','PRINCIPAL','COD_CONTRATO','PRAZO_PAGAMENTO','PESO','VOLUME','N_CAMADAS_PALETE','QTD_PRODUTOS_CAMADAS_PALETE','COD_GRUPO_LOJA','COD_GRUPO_FORNECEDOR','SELL_IN'
	UNION ALL
	SELECT 
	'' ,
	CONVERT(VARCHAR,ART.C_PROVEEDOR_PRIMARIO),
	case SUC.C_SUCU_EMPR when 41 then '41CD' else DBO.[NORMALIZA_STRING](SUC.C_SUCU_EMPR) end,
	CONVERT(VARCHAR,SUC.C_ARTICULO),
	/*CONVERT(VARCHAR, cast(PROV.Q_FACTOR_PROVEEDOR/SUC.Q_FACTOR_VTA_SUCU as decimal (10,2))), Corregido para que tome el mismo valor que en la tabla de productos*/
	--CONVERT(VARCHAR, cast(PROV.Q_FACTOR_PROVEEDOR as decimal (10,2))),
	CASE WHEN ART.M_VENDE_POR_PESO = 'N' THEN convert (varchar,prov.Q_FACTOR_PROVEEDOR) ELSE CONVERT(VARCHAR,ART.Q_PESO_UNIT_ART) END, /*SE AGREGA ESTA LINEA PARA IDENTIFICAR LO QUE VIENE POR PESABLE EL FACTOR SON LOS KILOS, SINO ES EL FACTOR PROVEEDOR EN UNIDADES POR BULTO.*/--QTDE_UNID_COMPRA
	--DBO.[NORMALIZA_STRING](COD.D_CODIGO_ABREV), --T001 TABLA CODIGO JOIN UNIDAD DE MEDIDA TABLA T050
	CASE WHEN ART.M_VENDE_POR_PESO = 'N' THEN 'UNID' ELSE 'KG' END,
	CONVERT(VARCHAR,COSTOS.I_LISTA_CALCULADO),
	'2999-12-31',
	'',
	cast(round(((1+isnull(PROV1.Q_DIAS_PREPARACION,0)+isnull(U_DIA_SEMANA_OC_LIMITE,0))*1.5),0) as varchar(10)),
	'1',
	'',
	'',
	null,
	null,
	null,
	null,
	'',
	'',
	'' 
	FROM [DIARCOP001].[DIARCOP].dbo.T051_ARTICULOS_SUCURSAL SUC WITH(NOLOCK) 
					inner JOIN [DIARCOP001].[DIARCOP].dbo.T050_ARTICULOS ART WITH(NOLOCK)  ON ART.C_ARTICULO=SUC.C_ARTICULO
				    inner JOIN [DIARCOP001].[DIARCOP].dbo.T052_ARTICULOS_PROVEEDOR PROV WITH(NOLOCK)  ON SUC.C_ARTICULO=PROV.C_ARTICULO AND ART.C_PROVEEDOR_PRIMARIO=PROV.C_PROVEEDOR and ART.C_ARTICULO=PROV.C_ARTICULO
					inner JOIN [DIARCOP001].[DIARCOP].dbo.T001_TABLA_CODIGO COD WITH(NOLOCK)  ON COD.C_CODIGO_TABLA=ART.C_UNIDAD_MEDIDA AND COD.C_TABLA=79
					inner JOIN [DIARCOP001].[DIARCOP].dbo.T055_ARTICULOS_CONDCOMPRA_COSTOS COSTOS WITH(NOLOCK)  ON COSTOS.C_ARTICULO=SUC.C_ARTICULO AND COSTOS.C_SUCU_EMPR=SUC.C_SUCU_EMPR AND COSTOS.C_PROVEEDOR=ART.C_PROVEEDOR_PRIMARIO
					left join [DIARCOP001].[DiarcoP].[dbo].[T020_PROVEEDOR_DIAS_ENTREGA_DETA] PROV1 WITH(NOLOCK)  on PROV1.C_PROVEEDOR=ART.C_PROVEEDOR_PRIMARIO and  PROV1.C_SUCU_EMPR=suc.C_SUCU_EMPR
					inner join [DIARCOP001].[DIARCOP].DBO.T100_EMPRESA_SUC SUC1 WITH(NOLOCK)  on SUC1.C_SUCU_EMPR=SUC.C_SUCU_EMPR
WHERE	    SUC1.C_SUCU_EMPR NOT IN (6,8,14,17,39,40,300, 80, 81, 83, 84, 88)
AND     SUC1.M_SUCU_VIRTUAL = 'N'
AND      SUC1.C_SUCU_EMPR NOT IN (SELECT C_SUCU_EMPR FROM [DIARCOP001].[DiarcoP].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA_DB] WITH(NOLOCK) )
and art.M_BAJA='N' 
END;


GO


