USE [kikker]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIKKER_T_87_PRECIO_PRODUCTOS_TIENDA]    Script Date: 19/06/2025 15:53:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_KIKKER_T_87_PRECIO_PRODUCTOS_TIENDA]
AS 

/*DATA	Fecha
COD_PRODUTO 	Código Producto
COD_LOJA 	Código Tienda
PRECO_UNIT_VAREJO  	Precio Unitario al Por menor
PRECO_UNIT_ATACADO  	Precio unitario Mayorista
PRECO_PROMOCIONAL  	Precio Promocional*/

BEGIN
SET NOCOUNT ON;

select 'DATA','COD_PRODUTO','COD_LOJA','PRECO_UNIT_VAREJO','PRECO_UNIT_ATACADO','PRECO_PROMOCIONAL' union all
select 
replace(convert(varchar,getdate(),111),'/','-'),
CAST(ART_SUC.C_ARTICULO AS VARCHAR (20)) ,--Codigo Articulo
case ART_SUC.C_SUCU_EMPR when 41 then '41CD' else DBO.[NORMALIZA_STRING](ART_SUC.C_SUCU_EMPR) end, --Sucursal
CAST(cast(ART_SUC.I_PRECIO_VTA*(1+isnull(PAR.K_RECAR_VTA_ESP,0)) AS MONEY) AS VARCHAR(40)),--Precio unitario al por menor. Usa factor por venta por menor volumen
CAST(ART_SUC.I_PRECIO_VTA AS VARCHAR (20)), --Percio Mayorista
CAST(ART_SUC.I_PRECIO_VTA AS VARCHAR (20)) --Precio Promocional
from [DIARCOP001].[DIARCOP].dbo.[T051_ARTICULOS_SUCURSAL]  ART_SUC
inner join [DIARCOP001].[DIARCOP].dbo.T050_ARTICULOS ART ON ART.C_ARTICULO=ART_SUC.C_ARTICULO 
left join [DIARCOP001].[DIARCOP].dbo.T230_FACTURADOR_PARAM_FLIA PAR on PAR.C_FAMILIA=ART.C_FAMILIA  AND PAR.C_SUCU_EMPR=ART_SUC.C_SUCU_EMPR
INNER JOIN [DIARCOP001].[DIARCOP].DBO.T100_EMPRESA_SUC SUC on ART_SUC.C_SUCU_EMPR=SUC.C_SUCU_EMPR
 where SUC.C_SUCU_EMPR NOT IN (6,8,14,17,39,40,300, 80, 81, 83, 84, 88)
AND SUC.M_SUCU_VIRTUAL = 'N'
AND SUC.C_SUCU_EMPR NOT IN (SELECT C_SUCU_EMPR FROM [DIARCOP001].[DiarcoP].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA_DB])
/*where AND PV.M_VIGENTE='S'*/
UNION ALL
select --DIARCO-BARRIO
replace(convert(varchar,getdate(),111),'/','-'),
CAST(ART_SUC.C_ARTICULO AS VARCHAR (20)), --Codigo Articulo
CAST(ART_SUC.C_SUCU_EMPR AS VARCHAR (20)), --Sucursal
CAST(CAST(ART_SUC.I_PRECIO_VTA*(1+isnull(PAR.K_RECAR_VTA_ESP,0)) AS MONEY) AS VARCHAR(40)),--Precio unitario al por menor. Usa factor por venta por menor volumen
CAST(ART_SUC.I_PRECIO_VTA AS VARCHAR (20)), --Percio Mayorista
CAST(ART_SUC.I_PRECIO_VTA AS VARCHAR (20)) --Precio Promocional
from [DIARCO-BARRIO].[DIARCOBARRIO].dbo.[T051_ARTICULOS_SUCURSAL]  ART_SUC
inner join [DIARCO-BARRIO].[DIARCOBARRIO].dbo.T050_ARTICULOS ART ON ART.C_ARTICULO=ART_SUC.C_ARTICULO 
left join [DIARCO-BARRIO].[DIARCOBARRIO].dbo.T230_FACTURADOR_PARAM_FLIA PAR on PAR.C_FAMILIA=ART.C_FAMILIA AND PAR.C_SUCU_EMPR=ART_SUC.C_SUCU_EMPR
INNER JOIN [DIARCOP001].[DIARCOP].DBO.T100_EMPRESA_SUC SUC on ART_SUC.C_SUCU_EMPR=SUC.C_SUCU_EMPR
 where SUC.C_SUCU_EMPR NOT IN (6,8,14,17,39,40,300, 80, 81, 83, 84, 88)
AND SUC.M_SUCU_VIRTUAL = 'N'
AND SUC.C_SUCU_EMPR NOT IN (SELECT C_SUCU_EMPR FROM [DIARCOP001].[DiarcoP].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA_DB]);
/*where AND PV.M_VIGENTE='S'*/;
end;

 
GO


