USE [kikker]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIKKER_T_11_2_PROMOCIONES_PRODUCTO_BKP]    Script Date: 19/06/2025 15:48:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_KIKKER_T_11_2_PROMOCIONES_PRODUCTO_BKP]
AS 

/*CODIGO_PROMOCAO 	Código Promoción
COD_PRODUTO 	Código Producto
COD_LOJA	Código Tienda
VALOR_PROMOCIONAL	Precio producto en promoción*/
SET NOCOUNT ON;

BEGIN
	
Select 'CODIGO_PROMOCAO','COD_PRODUTO','COD_LOJA','VALOR_PROMOCIONAL' union all
select 
distinct  
cast(ART_SUC.C_ARTICULO as varchar(5)),
cast(ART_SUC.C_ARTICULO as varchar(5)),
case ART_SUC.C_SUCU_EMPR when 41 then '41CD' else DBO.[NORMALIZA_STRING](ART_SUC.C_SUCU_EMPR) end,
cast(ART_SUC.I_PRECIO_VTA as varchar(10))
from  [DIARCOP001].[DIARCOP].dbo.[T051_ARTICULOS_SUCURSAL] ART_SUC
inner join [DIARCOP001].[DiarcoP].dbo.t050_articulos ART on ART_SUC.C_ARTICULO=ART.C_ARTICULO
inner join [DIARCOP001].[DIARCOP].DBO.T100_EMPRESA_SUC SUC on SUC.C_SUCU_EMPR=ART_SUC.C_SUCU_EMPR
WHERE	    SUC.C_SUCU_EMPR NOT IN (6,8,14,17,39,40,300, 80, 81, 83, 84, 88)
AND     SUC.M_SUCU_VIRTUAL = 'N'
AND      SUC.C_SUCU_EMPR NOT IN (SELECT C_SUCU_EMPR FROM [DIARCOP001].[DiarcoP].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA_DB])
and M_OFERTA_SUCU='S';

END;


--group by ART.C_ARTICULO,ART.N_ARTICULO
GO


