USE [kikker]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIKKER_M_1_MERCADOLOGICO]    Script Date: 19/06/2025 15:37:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_KIKKER_M_1_MERCADOLOGICO]
AS
BEGIN

/*
USE DIARCOP
NIVEL 1
COD_ERP_DEPARTAMENTO - Código do ERP para o Departamento
NOME_DEPARTAMENTO - Descrição do Departamento
NIVEL 2
COD_ERP_SETOR - Código do ERP para o Setor
NOME_SETOR - Descrição para o Setor
NIVEL 3
COD_ERP_GRUPO - Código do ERP para grupo
NOME_GRUPO - Descrição para o Grupo
NIVEL 4
COD_ERP_SUBGRUPO - Código do ERP para o subgrupo
NOME_SUBGRUPO - Descrição para o subgrupo
*/

SET NOCOUNT ON;
    CREATE TABLE ##TEMP_MERCADOLOGICO_KIKKER	(
	C_ARTICULO			decimal(10, 0) 	NULL DEFAULT 0,
	C_FAMILIA 			decimal(10, 0) 	NULL DEFAULT 0,
	C_RUBRO  			decimal(10, 0) 	NULL DEFAULT  0,
	C_SUBRUBRO_1  		decimal(10, 0) 	NULL DEFAULT  0,
	C_SUBRUBRO_2 		decimal(10, 0) 	NULL DEFAULT  0,
	C_SUBRUBRO_3		DECIMAL(10,0)	NULL DEFAULT 0,
	C_SUBRUBRO_4		DECIMAL(10,0)	NULL DEFAULT 0,
	N_FAMILIA     		CHAR(100)        NULL ,
	N_RUBRO      		CHAR(100)      	NULL ,
	N_SUBRUBRO_1     	CHAR(100)      	NULL ,
	N_SUBRUBRO_2     	CHAR(100)        NULL ,
	N_SUBRUBRO_3		CHAR(100)		NULL ,
	N_SUBRUBRO_4		CHAR(100)		NULL )


	INSERT INTO ##TEMP_MERCADOLOGICO_KIKKER
	SELECT	
	C_ARTICULO,
	case C_FAMILIA when 0 then 999 else C_FAMILIA end, 
	case C_RUBRO when 0 then 999 else C_RUBRO end, 
	case C_SUBRUBRO_1 when 0 then 999 else C_SUBRUBRO_1 end, 
	case C_SUBRUBRO_2 when 0 then 999 else C_SUBRUBRO_2 end, 
	case C_SUBRUBRO_3 when 0 then 999 else C_SUBRUBRO_3 end, 
	case C_SUBRUBRO_4 when 0 then 999 else C_SUBRUBRO_4 end,
	'SIN CLASIFICAR','SIN CLASIFICAR','SIN CLASIFICAR','SIN CLASIFICAR','SIN CLASIFICAR','SIN CLASIFICAR'
	FROM	[DIARCOP001].[DiarcoP].dbo.T050_ARTICULOS 
	WHERE	C_ARTICULO NOT IN (SELECT C_ARTICULO FROM [DIARCOP001].[DiarcoP].dbo.T050_ARTICULOS_DIFERENCIAS_DE_PRECIOS)

	UPDATE ##TEMP_MERCADOLOGICO_KIKKER
	   SET N_FAMILIA = T2.D_RUBRO /*,  C_FAMILIA = T2.C_RUBRO*/
	FROM ##TEMP_MERCADOLOGICO_KIKKER T1 , [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2
	WHERE T1.C_FAMILIA = T2.C_RUBRO
	AND	T2.C_RUBRO_PADRE = 0
	AND T2.C_RUBRO_NIVEL = 1
	
	UPDATE ##TEMP_MERCADOLOGICO_KIKKER
	   SET N_RUBRO = T2.D_RUBRO /*,C_RUBRO = T2.C_RUBRO*/
	FROM ##TEMP_MERCADOLOGICO_KIKKER T1 , [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2
	WHERE T1.C_RUBRO = T2.C_RUBRO
	  AND T1.C_RUBRO <> 0 
	
	UPDATE ##TEMP_MERCADOLOGICO_KIKKER
	   SET N_SUBRUBRO_1 = T2.D_RUBRO /*, C_SUBRUBRO_1=T2.C_RUBRO*/
	FROM ##TEMP_MERCADOLOGICO_KIKKER T1 , [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2
	WHERE T1.C_SUBRUBRO_1 = T2.C_RUBRO
	  AND T1.C_SUBRUBRO_1 <> 0
	
	UPDATE ##TEMP_MERCADOLOGICO_KIKKER
	   SET N_SUBRUBRO_2 = T2.D_RUBRO /*, C_SUBRUBRO_2=T2.C_RUBRO*/
	FROM ##TEMP_MERCADOLOGICO_KIKKER T1 , [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2
	WHERE T1.C_SUBRUBRO_2 = T2.C_RUBRO
	  AND T1.C_SUBRUBRO_2 <> 0

	UPDATE ##TEMP_MERCADOLOGICO_KIKKER
	   SET N_SUBRUBRO_3 = T2.D_RUBRO /*, C_SUBRUBRO_3=T2.C_RUBRO*/
	FROM ##TEMP_MERCADOLOGICO_KIKKER T1 , [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2
	WHERE T1.C_SUBRUBRO_3 = T2.C_RUBRO
	  AND T1.C_SUBRUBRO_3 <> 0

	UPDATE ##TEMP_MERCADOLOGICO_KIKKER
	   SET N_SUBRUBRO_4 = T2.D_RUBRO /*, C_SUBRUBRO_4 = T2.C_RUBRO*/
	FROM ##TEMP_MERCADOLOGICO_KIKKER T1 , [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2
	WHERE T1.C_SUBRUBRO_4 = T2.C_RUBRO
	  AND T1.C_SUBRUBRO_4 <> 0

	SELECT 'COD_ERP_DEPARTAMENTO','NOME_DEPARTAMENTO','COD_ERP_SETOR','NOME_SETOR','COD_ERP_GRUPO','NOME_GRUPO','COD_ERP_SUBGRUPO','NOME_SUBGRUPO'
	UNION ALL
	SELECT distinct cast(C_RUBRO as varchar(4)),
		   DBO.[NORMALIZA_STRING](N_RUBRO),
		   cast(C_SUBRUBRO_1 as varchar(4)),
		   DBO.[NORMALIZA_STRING](N_SUBRUBRO_1),
		   cast(C_SUBRUBRO_2 as varchar(4)),
		   DBO.[NORMALIZA_STRING](N_SUBRUBRO_2),
		   cast(C_SUBRUBRO_3 as varchar(4)),
		   DBO.[NORMALIZA_STRING](N_SUBRUBRO_3)
	FROM	##TEMP_MERCADOLOGICO_KIKKER 

DROP TABLE  ##TEMP_MERCADOLOGICO_KIKKER


END;
GO


