USE [kikker]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIKKER_T_7_PEDIDOS_PENDIENTES]    Script Date: 19/06/2025 15:52:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_KIKKER_T_7_PEDIDOS_PENDIENTES] AS
/*
8. diario de pedidos pendiente
q_unid_gramos_saldo t081_oc_deta / t081_oc_deta_DBARRIO

DATA_EMISSAO - Data da emissão pedido (formato AAAA-MM-DD)
DATA_ENTREGA - Data prevista para entrega do pedido (formato AAAA-MM-DD)
COD_PRODUTO - Código do produto comprado
COD_LOJA - Código da loja
QTDE_PEDIDA - Quantidade pedida para esse produto (unidade de venda)
NUMERO_DO_PEDIDO - Número do pedido que esse produto faz parte
COD_FORNCEDOR	Código Proveedor
*/

/*
Modificación 17/05/2023 - Maxi Argiro - Mail Hernan L.
(DETA.Q_BULTOS_PROV_PED*DETA.Q_FACTOR_PROV_PED)  - DETA.Q_UNID_CUMPLIDAS) <> 0 se saca esta condición 17/05
	M_CUMPLIDA_PARCIAL = 'N' AND ((Q_BULTOS_PROV_PED * Q_FACTOR_PROV_PED) < Q_UNID_CUMPLIDAS) se agrega la siguiente.
*/
BEGIN
SET NOCOUNT ON;

  -- declare @fecha date=getdate()-1;	

   SELECT 'DATA_EMISSAO','DATA_ENTREGA','COD_PRODUTO','COD_LOJA','QTDE_PEDIDA','NUMERO_DO_PEDIDO','COD_FORNECEDOR'
   UNION ALL
	SELECT distinct
	REPLACE(CONVERT(VARCHAR,CABE.F_EMISION,111),'/','-'),
	REPLACE(CONVERT(VARCHAR,CABE.F_ENTREGA,111),'/','-'),
	CONVERT(VARCHAR,DETA.C_ARTICULO),
	case CABE.C_SUCU_DESTINO when 41 then '41CD' else DBO.[NORMALIZA_STRING](CABE.C_SUCU_DESTINO) end,
	--CONVERT(VARCHAR,(DETA.Q_BULTOS_PROV_PED*DETA.Q_FACTOR_PROV_PED)  - DETA.Q_UNID_CUMPLIDAS),
	case Q_PESO_UNIT_ART when 0 then
	CONVERT(VARCHAR,(DETA.Q_BULTOS_PROV_PED*DETA.Q_FACTOR_PROV_PED)  - DETA.Q_UNID_CUMPLIDAS) 
	else CONVERT(VARCHAR,Q_PESO_TOTAL_PED-Q_PESO_CUMPLIDO) end,
	right('0000'+CONVERT(VARCHAR,DETA.U_PREFIJO_OC),4) + right('0000'+convert(varchar,deta.U_SUFIJO_OC),5),
	CONVERT(VARCHAR,CABE.C_PROVEEDOR)
	FROM	[DIARCOP001].[DIARCOP].dbo.T080_OC_CABE CABE 
			INNER JOIN [DIARCOP001].[DIARCOP].dbo.t081_oc_deta DETA ON CABE.U_SUFIJO_OC=DETA.U_SUFIJO_OC 
					AND CABE.U_PREFIJO_OC=DETA.U_PREFIJO_OC 
					AND CABE.C_OC=DETA.C_OC 
			INNER JOIN [DIARCOP001].[DIARCOP].DBO.T100_EMPRESA_SUC SUC on CABE.C_SUCU_DESTINO=SUC.C_SUCU_EMPR
	WHERE 
	--(DETA.Q_BULTOS_PROV_PED*DETA.Q_FACTOR_PROV_PED)  - DETA.Q_UNID_CUMPLIDAS <> 0 and --se saca esta condición 17/05*/
	M_CUMPLIDA_PARCIAL = 'N' AND ((Q_BULTOS_PROV_PED * Q_FACTOR_PROV_PED) > Q_UNID_CUMPLIDAS) /*Se agrega esta condición a pedido de Hernan 17/05*/
	AND  CABE.C_SITUAC = 1  
	AND	F_ALTA_SIST >='01/01/2022'
	and SUC.C_SUCU_EMPR NOT IN (6,8,14,17,39,40,300, 80, 81, 83, 84, 88)
	AND     SUC.M_SUCU_VIRTUAL = 'N'
	AND      SUC.C_SUCU_EMPR NOT IN (SELECT C_SUCU_EMPR FROM [DIARCOP001].[DiarcoP].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA_DB])                
	--AND F_ENTREGA > @fecha*/;
union all
SELECT  distinct
REPLACE(CONVERT(VARCHAR,T1.F_TRANSF,111),'/','-'),
REPLACE(CONVERT(VARCHAR,T1.F_ESTIMADA_LLEGADA,111),'/','-'),
CONVERT(VARCHAR,T2.C_ARTICULO),
case T1.C_SUCU_DEST when 41 then '41CD' else DBO.[NORMALIZA_STRING](T1.C_SUCU_DEST) end,
CONVERT(VARCHAR,T2.Q_UNID_PESO_TRANSF - T2.Q_UNID_PESO_RECEP),  --unidades pendientes
right('0000'+CONVERT(VARCHAR,T1.U_PREFIJO_REMITO),4) + right('0000'+convert(varchar,T1.U_SUFIJO_REMITO),5),
CONVERT(varchar,T3.C_PROVEEDOR_PRIMARIO)
FROM     [DIARCOP001].[DIARCOP].DBO.[T078_STOCK_CONTROL_TRANSF_CABE] T1,
         [DIARCOP001].[DIARCOP].DBO.[T078_STOCK_CONTROL_TRANSF_DETA] T2,
         [DIARCOP001].[DIARCOP].DBO.[T050_ARTICULOS]  T3
WHERE   T1.C_TRANSF = T2.C_TRANSF
AND        T1.U_PREFIJO_REMITO = T2.U_PREFIJO_REMITO
AND        T1.U_SUFIJO_REMITO = T2.U_SUFIJO_REMITO
AND        T2.C_ARTICULO =  T3.C_ARTICULO
AND        T2.Q_UNID_PESO_TRANSF <> T2.Q_UNID_PESO_RECEP  -- TRANSFERIDO DISTINTO DE RECIBIDO
AND        T2.Q_UNID_PESO_TRANSF > T2.Q_UNID_PESO_RECEP -- TRANSFERIDO MAYOR A RECIBIDO (POR SI RECIBIERON MAS DE LO ENVIADO)
AND        T2.M_CUMPL_MANUAL = 'N' -- POR SI LA GENTE DE TRANSITO DIO POR CUMPLIDA LA TRANSFERENCIA Y ACTUO SOBRE EL FALTANTE
AND        T1.C_SUCU_ORIG in ( 41,82) -- ORIGEN BASE 2
AND        T3.C_FAMILIA NOT IN (1,9,12) -- SE EXCLUYEN FAMILIAS VARIOS, FLETES Y PUBLICIDAD LA NO SER ARTICULOS VENDIBLES
AND        T1.C_SITUAC = 1; -- PENDIENTES

END;
GO


