USE [kikker]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIKKER_M_96_STOCK_SEGURIDAD]    Script Date: 19/06/2025 15:46:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_KIKKER_M_96_STOCK_SEGURIDAD]
AS 
/*
USE DIARCOP
ID
DC_NOMBRE
Trae todas las tiendas abiertas y cerradas. No mantienen el maestro de tiendas
*/
begin 
SET NOCOUNT ON;
	select 'COD_PROV','COD_ART','COD_SUC','DIA_STOCK' union all
	SELECT CAST(ART_COST.C_PROVEEDOR AS VARCHAR(10)),
	CAST(ART_COST.C_ARTICULO AS VARCHAR(10)),
	case ART_COST.C_SUCU_EMPR when 41 then '41CD' else DBO.[NORMALIZA_STRING](ART_COST.C_SUCU_EMPR) end,
	CAST(ART_COST.Q_DIAS_STOCK + ART_COST.Q_DIAS_SOBRE_STOCK  AS VARCHAR(10)) 
	FROM [DIARCOP001].[DiarcoP].[dbo].[T055_ARTICULOS_CONDCOMPRA_COSTOS] ART_COST
	inner join [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS] ART on ART.C_PROVEEDOR_PRIMARIO= ART_COST.C_PROVEEDOR and ART.C_ARTICULO=ART_COST.C_ARTICULO
	inner join [DIARCOP001].[DIARCOP].DBO.T100_EMPRESA_SUC SUC_MAE on SUC_MAE.C_SUCU_EMPR=ART_COST.C_SUCU_EMPR and ART_COST.C_SUCU_EMPR not in (6,8,14,17,39,40,300, 80, 81, 83, 84, 88) and SUC_MAE.M_SUCU_VIRTUAL = 'N'
	AND      ART_COST.C_SUCU_EMPR NOT IN (SELECT C_SUCU_EMPR FROM [DIARCOP001].[DiarcoP].[dbo].[T900_SUCURSALES_EXCLUIDAS_GERENCIA_DB])
end;
	


GO


