USE [kikker]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIKKER_M_3_2_FAMILIA_PRODUCTO]    Script Date: 19/06/2025 15:38:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_KIKKER_M_3_2_FAMILIA_PRODUCTO]
AS 

BEGIN
	SET NOCOUNT ON;
	SELECT 'COD_FAMILIA','COD_PRODUTO'
	union all
	SELECT	
	distinct cast(C_CLASIFICACION_COMPRA as varchar(10)),
	cast(C_ARTICULO as varchar(10))
		FROM	[DIARCOP001].[DIARCOP].dbo.T050_ARTICULOS
	WHERE	C_ARTICULO NOT IN (SELECT C_ARTICULO FROM [DIARCOP001].[DIARCOP].dbo.T050_ARTICULOS_DIFERENCIAS_DE_PRECIOS) --AND
	--C_CLASIFICACION_COMPRA in (1,6) /*CONDICIÓN de ARTICULOS SENSIBLES*/
	AND		M_BAJA = 'N'
	
END

GO


