USE [kikker]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIKKER_M_3_1_FAMILIA]    Script Date: 19/06/2025 15:38:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_KIKKER_M_3_1_FAMILIA]
AS
BEGIN

/*
USE DIARCOP
COD_FAMILIA	Código Familia del Producto
NOME_FAMILIA	Nombre de la Familia
*/

SET NOCOUNT ON;
 --   CREATE TABLE #TEMP_FAMILIA_KIKKER	(
	--C_FAMILIA 			decimal(5, 0) 	NULL DEFAULT 0,
	--N_FAMILIA     		CHAR(30)      	NOT NULL DEFAULT ''  )


	--INSERT INTO #TEMP_FAMILIA_KIKKER
	--SELECT	C_FAMILIA,''
	--FROM	[DIARCOP001].[DiarcoP].dbo.T050_ARTICULOS 

	--UPDATE #TEMP_FAMILIA_KIKKER
	--   SET N_FAMILIA = T2.D_RUBRO/*,  C_FAMILIA = T2.C_RUBRO*/
	--FROM #TEMP_FAMILIA_KIKKER T1 , [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2
	--WHERE T1.C_FAMILIA = T2.C_RUBRO
	--AND	T2.C_RUBRO_PADRE = 0
	--AND T2.C_RUBRO_NIVEL = 1

	--SELECT 'COD_FAMILIA','NOME_FAMILIA'
	--UNION ALL
	--SELECT distinct cast(C_FAMILIA as varchar(4)),
	--DBO.[NORMALIZA_STRING](N_FAMILIA)
	--FROM	#TEMP_FAMILIA_KIKKER 

	CREATE TABLE #TEMP_FAMILIA_KIKKER	(
	C_FAMILIA 			decimal(5, 0) 	NULL DEFAULT 0,
	N_FAMILIA     		CHAR(30)      	NOT NULL DEFAULT ''  )


	INSERT INTO #TEMP_FAMILIA_KIKKER
	SELECT	C_CLASIFICACION_COMPRA,''
	FROM	[DIARCOP001].[DiarcoP].dbo.T050_ARTICULOS 

	UPDATE #TEMP_FAMILIA_KIKKER
	   SET N_FAMILIA = T2.D_CODIGO /*,  C_FAMILIA = T2.C_RUBRO*/
	FROM #TEMP_FAMILIA_KIKKER T1 , [DIARCOP001].[DiarcoP].dbo.T001_TABLA_CODIGO T2
	WHERE T1.C_FAMILIA = T2.C_CODIGO_TABLA
	AND	T2.C_TABLA = 119
	

	SELECT 'COD_FAMILIA','NOME_FAMILIA'
	UNION ALL
	SELECT distinct cast(C_FAMILIA as varchar(4)),
	DBO.[NORMALIZA_STRING](N_FAMILIA)
	FROM	#TEMP_FAMILIA_KIKKER 
	
	


	DROP TABLE #TEMP_FAMILIA_KIKKER
END;
GO


