USE [data-sync]
GO

/****** Object:  Table [dbo].[T050_ARTICULOS]    Script Date: 11/02/2025 16:57:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T085_ARTICULOS_EAN](
	[C_ARTICULO] [numeric](6, 0) NOT NULL,
	[C_EAN] [char](14) NOT NULL,
	[C_TIPO][int] NULL
) ON [PRIMARY]
GO

INSERT INTO [dbo].[T085_ARTICULOS_EAN] (C_ARTICULO, C_EAN, C_TIPO)
SELECT C_ARTICULO, C_EAN, LEN(C_EAN) FROM [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS]  WHERE C_EAN IS NOT NULL
UNION ALL
SELECT C_ARTICULO, C_DUN14 , LEN(C_DUN14)FROM [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS] WHERE C_DUN14 IS NOT NULL
UNION ALL
SELECT C_ARTICULO, C_EAN_ALTERNATIVO_1, LEN(C_EAN_ALTERNATIVO_1) FROM [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS] WHERE C_EAN_ALTERNATIVO_1 IS NOT NULL
UNION ALL
SELECT C_ARTICULO, C_EAN_ALTERNATIVO_2, LEN(C_EAN_ALTERNATIVO_2) FROM [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS] WHERE C_EAN_ALTERNATIVO_2 IS NOT NULL
UNION ALL
SELECT C_ARTICULO, C_EAN_ALTERNATIVO_3, LEN(C_EAN_ALTERNATIVO_3) FROM [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS] WHERE C_EAN_ALTERNATIVO_3 IS NOT NULL
UNION ALL
SELECT C_ARTICULO, C_EAN_ALTERNATIVO_4, LEN(C_EAN_ALTERNATIVO_4) FROM [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS] WHERE C_EAN_ALTERNATIVO_4 IS NOT NULL;
