USE [kikker]
GO

/****** Object:  StoredProcedure [dbo].[SP_ZEETREX_T_710_ESTADIS_REPOSICION]    Script Date: 25/09/2024 9:03:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DECLARE @dia_ant varchar(10) = FORMAT(GETDATE()-1,'yyyy-MM-dd') 

	SELECT 'C_SUCU_EMPR','C_ARTICULO','Q_VENTA_30_DIAS','Q_VENTA_15_DIAS','Q_VENTA_DOMINGO','Q_VENTA_ESPECIAL_30_DIAS','Q_VENTA_ESPECIAL_15_DIAS','Q_DIAS_CON_STOCK','Q_REPONER'
	,'Q_REPONER_INCLUIDO_SOBRE_STOCK','M_SEMAFORO_INDIVIDUAL','M_SEMAFORO_GLOBAL','Q_VENTA_DIARIA_NORMAL','Q_DIAS_STOCK','Q_DIAS_SOBRE_STOCK','Q_DIAS_ENTREGA_PROVEEDOR','F_UPDATE','F_PROC'

	UNION ALL
	SELECT TOP 10 [C_SUCU_EMPR]
      ,[C_ARTICULO]
      ,[Q_VENTA_30_DIAS]
      ,[Q_VENTA_15_DIAS]
      ,[Q_VENTA_DOMINGO]
      ,[Q_VENTA_ESPECIAL_30_DIAS]
      ,[Q_VENTA_ESPECIAL_15_DIAS]
      ,[Q_DIAS_CON_STOCK]
      ,[Q_REPONER]
      ,[Q_REPONER_INCLUIDO_SOBRE_STOCK]
      ,[M_SEMAFORO_INDIVIDUAL]
      ,[M_SEMAFORO_GLOBAL]
      ,[Q_VENTA_DIARIA_NORMAL]
      ,[Q_DIAS_STOCK]
      ,[Q_DIAS_SOBRE_STOCK]
      ,[Q_DIAS_ENTREGA_PROVEEDOR]
	  ,FORMAT(GETDATE()-1,'yyyy-MM-dd')  as F_UPDATE
	  ,GETDATE() as F_PROC
  FROM [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_REPOSICION]


	

D:\Zeetrex\Temporal