
-------CREATE PROCEDURE [dbo].[SP_ZTRX_M_1_CATEGORIAS]
AS
BEGIN
    SET NOCOUNT ON;

    -- Eliminar la tabla si ya existe
    IF OBJECT_ID('dbo.M_1_CATEGORIAS', 'U') IS NOT NULL
    BEGIN
--        DROP TABLE dbo.M_1_CATEGORIAS;
    END

    -- Crear la tabla M_1_CATEGORIAS
    CREATE TABLE M_1_CATEGORIAS (
        C_RUBRO VARCHAR(4),
        N_RUBRO_NORMALIZADO VARCHAR(MAX),
        C_SUBRUBRO_1 VARCHAR(4),
        N_SUBRUBRO_1_NORMALIZADO VARCHAR(MAX),
        C_SUBRUBRO_2 VARCHAR(4),
        N_SUBRUBRO_2_NORMALIZADO VARCHAR(MAX),
        C_SUBRUBRO_3 VARCHAR(4),
        N_SUBRUBRO_3_NORMALIZADO VARCHAR(MAX),
		F_DATO DATETIME,  -- Fecha y hora de vigencia del dato
		F_PROC DATETIME  -- Fecha y hora de procesamiento
    );

    -- Insertar datos directamente en la tabla M_1_CATEGORIAS
    INSERT INTO M_1_CATEGORIAS (C_RUBRO, N_RUBRO_NORMALIZADO, C_SUBRUBRO_1, N_SUBRUBRO_1_NORMALIZADO, C_SUBRUBRO_2, N_SUBRUBRO_2_NORMALIZADO, C_SUBRUBRO_3, N_SUBRUBRO_3_NORMALIZADO,F_DATO, F_PROC)
    SELECT DISTINCT
        CAST(art.C_RUBRO AS VARCHAR(4)) AS C_RUBRO,
        DBO.[NORMALIZA_STRING](ISNULL(T2_RUBRO.D_RUBRO, 'SIN CLASIFICAR')) AS N_RUBRO_NORMALIZADO,
        CAST(art.C_SUBRUBRO_1 AS VARCHAR(4)) AS C_SUBRUBRO_1,
        DBO.[NORMALIZA_STRING](ISNULL(T2_SUBRUBRO_1.D_RUBRO, 'SIN CLASIFICAR')) AS N_SUBRUBRO_1_NORMALIZADO,
        CAST(art.C_SUBRUBRO_2 AS VARCHAR(4)) AS C_SUBRUBRO_2,
        DBO.[NORMALIZA_STRING](ISNULL(T2_SUBRUBRO_2.D_RUBRO, 'SIN CLASIFICAR')) AS N_SUBRUBRO_2_NORMALIZADO,
        CAST(art.C_SUBRUBRO_3 AS VARCHAR(4)) AS C_SUBRUBRO_3,
        DBO.[NORMALIZA_STRING](ISNULL(T2_SUBRUBRO_3.D_RUBRO, 'SIN CLASIFICAR')) AS N_SUBRUBRO_3_NORMALIZADO,
		GETDATE()-1 AS F_DATO, -- Fecha y hora actual en formato DATETIME
		GETDATE() AS F_PROC -- Fecha y hora actual en formato DATETIME

    FROM
        [DIARCOP001].[DiarcoP].dbo.T050_ARTICULOS art
        LEFT JOIN [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2_RUBRO ON art.C_RUBRO = T2_RUBRO.C_RUBRO AND T2_RUBRO.C_RUBRO_PADRE = 0 AND T2_RUBRO.C_RUBRO_NIVEL = 1
        LEFT JOIN [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2_SUBRUBRO_1 ON art.C_SUBRUBRO_1 = T2_SUBRUBRO_1.C_RUBRO
        LEFT JOIN [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2_SUBRUBRO_2 ON art.C_SUBRUBRO_2 = T2_SUBRUBRO_2.C_RUBRO
        LEFT JOIN [DIARCOP001].[DiarcoP].dbo.T114_RUBROS T2_SUBRUBRO_3 ON art.C_SUBRUBRO_3 = T2_SUBRUBRO_3.C_RUBRO
    WHERE
        art.C_ARTICULO NOT IN (SELECT C_ARTICULO FROM [DIARCOP001].[DiarcoP].dbo.T050_ARTICULOS_DIFERENCIAS_DE_PRECIOS);

END;
GO


