SELECT DISTINCT
	---	P.[C_SUCU_EMPR]
       S.[CLUSTER_LOG]
      ,P.[C_FAMILIA]
      ,P.[C_RUBRO]
      ,P.[Q_DIAS_STOCK]
      ,P.[Q_DIAS_SOBRE_STOCK]

  INTO T_CLUSTER_PARAM_STOCK
  FROM [data-sync].[dbo].[T055_ARTICULOS_PARAM_STOCK] P
  INNER JOIN [data-sync].[dbo].[T_100_SUCURSALES] S
  ON P.[C_SUCU_EMPR] = S.[C_SUCU_EMPR]
  ORDER BY S.CLUSTER_LOG, C_FAMILIA
