SELECT TOP (1000) [C_PROVEEDOR]
      ,[C_ARTICULO]
      ,[C_SUCU_EMPR]
      ,[Q_BULTOS_KILOS_DIARCO]
      ,[F_ALTA_SIST]
      ,[C_USUARIO_GENERO_OC]
      ,[C_TERMINAL_GENERO_OC]
      ,[F_GENERO_OC]
      ,[C_USUARIO_BLOQUEO]
      ,[M_PROCESADO]
      ,[F_PROCESADO]
      ,[U_PREFIJO_OC]
      ,[U_SUFIJO_OC]
      ,[C_COMPRA_KIKKER]
      ,[C_USUARIO_MODIF]
      ,[C_COMPRADOR]
  FROM [DiarcoP].[dbo].[T080_OC_PRECARGA_KIKKER]

SELECT  *
FROM	  T020_PROVEEDOR_GESTION_COMPRA
WHERE	  C_USUARIO = 'RGARFI'