/*** CONSULTA COMBINADA DE DATOS ***/
/***********************************/

USE [data-sync]
GO

WITH CTE_T_OC_CABECERA AS (
    SELECT DISTINCT CAST(F_ALTA_SIST AS DATE) AS FECHA_PROCESO
    FROM [dbo].[T_OC_CABECERA]
),
CTE_T_OC_DETALLE AS (
    SELECT DISTINCT CAST(F_EMISION AS DATE) AS FECHA_PROCESO
    FROM [dbo].[T_OC_DETALLE]
),
CTE_T_OC_DETALLE_EXT AS (
    SELECT DISTINCT CAST(F_EMISION AS DATE) AS FECHA_PROCESO
    FROM [dbo].[T_OC_DETALLE_EXT]
),
CTE_T_RECUPERO_PROVEEDORES AS (
    SELECT DISTINCT CAST(F_ALTA_SIST AS DATE) AS FECHA_PROCESO
    FROM [dbo].[T_RECUPERO_PROVEEDORES]
),
CTE_T_COMPETENCIA_DETALLE AS (
    SELECT DISTINCT CAST(F_ALTA AS DATE) AS FECHA_PROCESO
    FROM [dbo].[T_COMPETENCIA_DETALLE]
)

SELECT 
    COALESCE(A.FECHA_PROCESO, B.FECHA_PROCESO, C.FECHA_PROCESO, D.FECHA_PROCESO, E.FECHA_PROCESO) AS FECHA_BASE,
    A.FECHA_PROCESO AS FECHA_OC_CABECERA,
    B.FECHA_PROCESO AS FECHA_OC_DETALLE,
    C.FECHA_PROCESO AS FECHA_OC_DETALLE_EXT,
    D.FECHA_PROCESO AS FECHA_RECUPERO_PROVEEDORES,
    E.FECHA_PROCESO AS FECHA_COMPETENCIA_DETALLE
FROM CTE_T_OC_CABECERA A
FULL OUTER JOIN CTE_T_OC_DETALLE B 
    ON A.FECHA_PROCESO = B.FECHA_PROCESO
FULL OUTER JOIN CTE_T_OC_DETALLE_EXT C
    ON A.FECHA_PROCESO = C.FECHA_PROCESO
FULL OUTER JOIN CTE_T_RECUPERO_PROVEEDORES D
    ON A.FECHA_PROCESO = D.FECHA_PROCESO
FULL OUTER JOIN CTE_T_COMPETENCIA_DETALLE E
    ON A.FECHA_PROCESO = E.FECHA_PROCESO
ORDER BY FECHA_BASE ASC;


--- Recuento de Registros
USE [data-sync]
GO;

SELECT COUNT (*) as CABECERA FROM [data-sync].[dbo].[T_OC_CABECERA] 
SELECT COUNT (*) as DETALLE FROM [data-sync].[dbo].[T_OC_DETALLE] 
SELECT COUNT (*) as DETALLE_EXT FROM [data-sync].[dbo].[T_OC_DETALLE_EXT]
SELECT COUNT (*) as RECUPEROS FROM [data-sync].[dbo].[T_RECUPERO_PROVEEDORES]
SELECT COUNT (*) as COMPETENCIA FROM [data-sync].[dbo].[T_COMPETENCIA_DETALLE]

