-- CONTROOL GENERAL DE LAS FECHAS PROCESADAS QUE EXISTEN EN LOS ARCHIVOS DE INTERFACES
---
--- CONTROLAR FECHAS:
SELECT DISTINCT CAST(F_ALTA_SIST AS DATE) AS FECHA_PROCESO
FROM [dbo].[T_OC_CABECERA]
ORDER BY FECHA_PROCESO ASC;

--- CONTROLAR FECHAS:
SELECT DISTINCT CAST([F_EMISION] AS DATE) AS FECHA_PROCESO
FROM [dbo].[T_OC_DETALLE]
ORDER BY FECHA_PROCESO ASC;

--- CONTROLAR FECHAS:
SELECT DISTINCT CAST([F_EMISION] AS DATE) AS FECHA_PROCESO
FROM [dbo].[T_OC_DETALLE_EXT]
ORDER BY FECHA_PROCESO ASC;

--- CONTROLAR FECHAS:
SELECT DISTINCT CAST([F_ALTA_SIST] AS DATE) AS FECHA_PROCESO
FROM [dbo].[T_RECUPERO_PROVEEDORES]
ORDER BY FECHA_PROCESO ASC;

--- CONTROLAR FECHAS:
SELECT DISTINCT CAST([F_ALTA] AS DATE) AS FECHA_PROCESO
FROM [dbo].[T_COMPETENCIA_DETALLE]
ORDER BY FECHA_PROCESO ASC;