-- CONTROL OC GENERADAS
-- CABECERA
SELECT *

into repl.T000_GESTION_COMPRA_PROVEEDOR_DETA_DIA_ANTERIOR

FROM [DIARCOP001].[DiarcoP].[dbo].T000_GESTION_COMPRA_PROVEEDOR_DETA_DIA_ANTERIOR
WHERE C_MOTIVO_SNC NOT IN (-1,-2,6)


-- WHERE C_PROVEEDOR = 190 AND CAST(F_ALTA_SIST AS DATE) = CAST(GETDATE() AS DATE);


-- DETALLE

SELECT TOP (1000) *
FROM [DiarcoP].[dbo].[T081_OC_DETA]
ORDER BY [U_SUFIJO_OC] DESC

------------------- ACA VA EL TABLA DE CONTROL
CREATE TABLE [repl].[T091_COMPETENCIA_PRECIOS_DETA_SYNC](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fecha_ejecucion] [datetime] NULL,
	[estado] [varchar](20) NULL,
	[mensaje] [nvarchar](4000) NULL,
	[registros_afectados] [int] NULL,
	[duracion_segundos] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

