USE CODER
GO

CREATE TABLE ESTUDIANTES
(
	EstudianteID INT NOT NULL,
	Apellido VARCHAR(20) NOT NULL,
	Nombre VARCHAR(30) NOT NULL,
	DNI VARCHAR(8) NOT NULL,	
	TelMovil VARCHAR(15) NULL,
	TelFijo VARCHAR(15) NULL,
	Dirección VARCHAR(50) NULL,
	Email VARCHAR(35) NULL,
	FechaNac DATE NULL,

	CONSTRAINT PK_EstudianteID
    PRIMARY KEY CLUSTERED (EstudianteID)  
)

CREATE INDEX Alfabetico
ON ESTUDIANTES(Apellido, Nombre);


CREATE TABLE PROFESORES
(
	ProfesorID INT NOT NULL,
	Apellido VARCHAR(20) NOT NULL,
	Nombre VARCHAR(30) NOT NULL,
	DNI VARCHAR(8) NOT NULL,	
	TelMovil VARCHAR(15) NULL,
	TelFijo VARCHAR(15) NULL,
	Dirección VARCHAR(50) NULL,
	Email VARCHAR(35) NULL,
	FechaNac DATE NULL,

	CONSTRAINT PK_ProfesorID
    PRIMARY KEY CLUSTERED (ProfesorID)  
)

CREATE INDEX Alfabetico
ON PROFESORES(Apellido, Nombre);


CREATE TABLE ASIGNATURAS
(
	AsignaturaID INT NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Descripcion VARCHAR(255) NOT NULL,
	HorasCatedra INT NULL,
	FechaInicio DATE NULL,
	FechaNac DATE NULL,

	CONSTRAINT PK_AsignaturaID
    PRIMARY KEY CLUSTERED (AsignaturaID)  
)
