SELECT TOP (1000) V.[F_VENTA]
      ,V.[C_ARTICULO]
---      ,V.[C_FAMILIA]
      ,V.[C_SUCU_EMPR]
      ,V.[I_PRECIO_VENTA]
      ,V.[I_PRECIO_COSTO]
      ,V.[I_VENDIDO]
      ,V.[Q_UNIDADES_VENDIDAS]
      ,V.[I_PRECIO_COSTO_PP]
      ,V.[I_PARTE_ULTIMO_INGRESO]
      ,V.[I_COMPRA_ULTIMO_INGRESO]
      ,V.[I_IMP_INTERNOS]

	  ,A.[C_ARTICULO]
      ,A.[C_FAMILIA]
      ,A.[C_RUBRO]
      ,A.[C_SUBRUBRO_1]
      ,A.[C_SUBRUBRO_2]
      ,A.[N_ARTICULO]
 
  FROM [DiarcoEst].[dbo].[T702_EST_VTAS_POR_ARTICULO] V
  LEFT JOIN [DiarcoEst].[dbo].[T050_ARTICULOS] A 
	ON V.C_ARTICULO = A.C_ARTICULO
WHERE V.C_ARTICULO BETWEEN  50 AND 100  AND
V.F_VENTA >='20240101'


