/*** ALGORITMOS PARA DEMANDA PYTHON  (UTILIZA: DiarcoEst SERVER=192.168.0.250 ***/

SELECT TOP (1000) V.[F_VENTA]
      ,V.[C_ARTICULO]
      ,V.[C_SUCU_EMPR]
      ,V.[Q_UNIDADES_VENDIDAS]
      ,V.[I_PRECIO_VENTA]
      ,V.[I_PRECIO_COSTO]
      ,V.[I_VENDIDO]
      ,V.[I_PRECIO_COSTO_PP]

      ,A.[C_FAMILIA]
      ,A.[C_RUBRO]
      ,A.[C_SUBRUBRO_1]
      ,A.[C_SUBRUBRO_2]
      ,A.[N_ARTICULO]
 
  FROM [DiarcoEst].[dbo].[T702_EST_VTAS_POR_ARTICULO] V
  LEFT JOIN [DiarcoEst].[dbo].[T050_ARTICULOS] A 
	ON V.C_ARTICULO = A.C_ARTICULO
WHERE V.C_ARTICULO BETWEEN  50 AND 100  AND
V.F_VENTA >='20240101'

 ORDER BY V.C_ARTICULO,V.[F_VENTA], C_SUCU_EMPR

 /** LOTE DE CONTROL ***/

 SELECT F_VENTA, C_ARTICULO, Q_UNIDADES_VENDIDAS
FROM [DiarcoEst].[dbo].[T702_EST_VTAS_POR_ARTICULO]
WHERE C_ARTICULO BETWEEN  50 AND 100  AND 
	F_VENTA BETWEEN CONVERT(DATE, '20241130') AND DATEADD(DAY, 30, CONVERT(DATE, '20241130'))