SELECT V.[F_VENTA]
      ,V.[C_ARTICULO]
      ,V.[C_SUCU_EMPR]
      ,V.[I_PRECIO_VENTA]
      ,V.[I_PRECIO_COSTO]
      ,V.[I_VENDIDO]
      ,V.[Q_UNIDADES_VENDIDAS]
      ,V.[I_PRECIO_COSTO_PP]
  
      ,V.[C_FAMILIA]
      ,A.[C_RUBRO]
      ,A.[C_SUBRUBRO_1]
      ,A.[C_SUBRUBRO_2]
      ,A.[N_ARTICULO]
 
  FROM [DiarcoEst].[dbo].[T702_EST_VTAS_POR_ARTICULO] V
  LEFT JOIN [DiarcoEst].[dbo].[T050_ARTICULOS] A 
	ON V.C_ARTICULO = A.C_ARTICULO
WHERE V.C_ARTICULO BETWEEN  50 AND 100  AND
V.F_VENTA >='20240101'

SELECT C_FAMILIA, C_RUBRO, C_SUBRUBRO_1, COUNT(C_ARTICULO)
	FROM [DiarcoEst].[dbo].[T050_ARTICULOS] 
	GROUP BY C_FAMILIA, C_RUBRO, C_SUBRUBRO_1
	ORDER BY C_FAMILIA, C_RUBRO, C_SUBRUBRO_1

SELECT COUNT(C_ARTICULO)
	FROM [DiarcoEst].[dbo].[T050_ARTICULOS]
	WHERE C_RUBRO BETWEEN 2053 AND 2055	

SELECT TOP 5000 * FROM [DiarcoEst].[dbo].[T050_ARTICULOS] 
	WHERE C_RUBRO BETWEEN 2053 AND 2055
	ORDER BY C_FAMILIA, C_RUBRO, C_SUBRUBRO_1, C_ARTICULO


/**** PARA PRUEBAS ***/
SELECT V.[F_VENTA]
      ,V.[C_ARTICULO]
      ,V.[C_SUCU_EMPR]
      ,V.[I_PRECIO_VENTA]
      ,V.[I_PRECIO_COSTO]
      ,V.[I_VENDIDO]
      ,V.[Q_UNIDADES_VENDIDAS]
      ,V.[I_PRECIO_COSTO_PP]
  
      ,V.[C_FAMILIA]
      ,A.[C_RUBRO]
      ,A.[C_SUBRUBRO_1]
      ,A.[C_SUBRUBRO_2]
      ,A.[N_ARTICULO]
 
  FROM [DiarcoEst].[dbo].[T702_EST_VTAS_POR_ARTICULO] V
  LEFT JOIN [DiarcoEst].[dbo].[T050_ARTICULOS] A 
	ON V.C_ARTICULO = A.C_ARTICULO
WHERE A.C_RUBRO BETWEEN 2053 AND 2055	AND
V.F_VENTA >='20240101'