USE [data-sync]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CNX_GENERAR_DATA_ELASTICIDAD]
@vchMensaje VARCHAR(255) = '' OUTPUT

AS
SET NOCOUNT ON

DECLARE @FechaDesde		AS DATETIME
DECLARE @FechaHasta		AS DATETIME
DECLARE @FechaStockDesde AS DATETIME
DECLARE @FechaStockHasta AS DATETIME
DECLARE @FechaOfFolDesde AS DATETIME
DECLARE @FechaOfFolHasta AS DATETIME
DECLARE @C_SUCU_EMPR	AS INT
DECLARE @C_ARTICULO		AS INT
DECLARE @F_CIERRE		AS DATETIME

--*** Autor: EWE**

--	Objetivo: Toma las tablas de estadísticas de ventas, stock y oferta y folder y genera registros en S_ELASTICIDAD_DETALLE
--	con fecha, sucursal, artículo, si es Domingo, si estuvo en oferta, si estuvo en folder y la venta del día y el stock que
--	tenía en apertura. Genera 30 días X cantidad de sucursales X cantidad de artículos
--	 Después genera en T710_ESTADIS_REPOSICION registros con sucursal, articulo, venta 30D, venta 15D, venta Domingo, venta especial 30D
--	venta especial 15D, dias normales (con stock, NO DOMINGO y NO OFERTA NI FOLDER), cantidad a reponer
--	 Ambas tablas se truncan antes de empezar. NO ES DESTRUCTIVO. SE PUEDE CORRER EN CUALQUIER MOMENTO DEL DIA. 
--	 Al 28/03/2013 en producción tarda 20 minutos
	 
--	 Esto sirve para alimentar la reposición de días normales que se va a mostrar en las pantallas de Gerencia

BEGIN

	SET @FechaDesde = NULL -- '20240101'
	SET @C_SUCU_EMPR = NULL
	SET @C_ARTICULO = NULL

	IF @FechaDesde IS NULL 
		SELECT @FechaDesde = F_CIERRE 
		FROM T900_FECHA_CIERRE

    -- CHRISTIAN 31/07/2023
	-- AGREGO ESTO PORQUE SINO SE PIERDEN LOS DATOS DE LA 300 (CORRE ANTES EN EL SERVIDOR DIARCO BARRIO)
	--truncate table diarcop.dbo.T999_ESTADIS_DETALLE
	
	--insert into dbo.T999_ESTADIS_DETALLE
	--select * from dbo.S_ELASTICIDAD_DETALLE 
	--where c_sucu_empr = 300

	-- FIN AGREGADO 31/07


	TRUNCATE TABLE S_ELASTICIDAD_DETALLE
	IF OBJECT_ID(N'tempdb..#TempFechas',N'U') IS NOT NULL
		DROP TABLE #TempFechas
		
	CREATE TABLE #TempFechas (
	datevalue datetime,
	FechaStock datetime,
	FechaOfertaYFolder datetime) 	
	
	
	CREATE INDEX IX_TEMP_FECHAS ON #TempFechas (		
		datevalue ASC,
		FechaStock ASC,
		FechaOfertaYFolder ASC
	) 	
		
	;
	WITH cte AS
		(
			SELECT DATEADD(DAY, -31, @FechaDesde) DateValue
			UNION ALL
			SELECT DateValue + 1
			FROM cte 
			WHERE DateValue + 1 <= @FechaDesde
		)

	INSERT INTO #TempFechas 
	SELECT *, 
		dbo.FechaCierreEstadisticoStock(DateValue) AS FechaStock, 
		dbo.FechaCierreOfertaYFolder(DateValue) AS FechaOfertaYFolder
	FROM cte

	SELECT @FechaStockDesde = MAX(FechaStock), 
		@FechaStockHasta = MIN(FechaStock), 
		@FechaOfFolDesde = MAX(FechaOfertaYFolder), 
		@FechaOfFolHasta = MIN(FechaOfertaYFolder)
	FROM #TempFechas


	--select * from #TempFechas
	--order by 1 desc


	INSERT INTO S_ELASTICIDAD_DETALLE
	SELECT DateValue, 
		T2.C_SUCU_EMPR,
		T2.C_ARTICULO, 
		CASE DATEPART(dw, T.DateValue) WHEN 7 THEN 'S' ELSE 'N' END,
		'N',
		'N',
		0,
		0,
	    'N'
	FROM  #TempFechas T
	LEFT JOIN T051_ARTICULOS_SUCURSAL T2
		ON T2.C_SUCU_EMPR < 300
		--and t2.c_articulo = 7146
	ORDER BY 1 DESC


	IF @@ERROR <> 0 
	    BEGIN
			SET @vchMensaje = 'Error en SQL < INSERT en S_ELASTICIDAD_DETALLE > en Stored Procedure SD99_CIERREGRAL_CALCULO_ESTADISTICA_DIAS_REPOSICION'
			RETURN 99
		END
                     
					
	--///////////////////////////////////////// INSERTO FOLDER ///////////////////////////////////////////////////////////////////


	UPDATE S_ELASTICIDAD_DETALLE 
	SET M_FOLDER = X.M_FOLDER
	FROM (
		SELECT T.DateValue,
			T.FechaOfertaYFolder, 
			FOL.C_SUCU_EMPR, 
			FOL.C_ARTICULO, 
			FOL.DIA AS M_FOLDER
		FROM #TempFechas T
		INNER JOIN
			(
			SELECT C_ANIO, 
				C_MES, 
				C_SUCU_EMPR, 
				C_ARTICULO, 
				CAST(M_FOLDER_DIA1  AS VARCHAR(1)) AS M_FOLDER_DIA1,  CAST(M_FOLDER_DIA2  AS VARCHAR(1)) AS M_FOLDER_DIA2, 
				CAST(M_FOLDER_DIA3  AS VARCHAR(1)) AS M_FOLDER_DIA3,  CAST(M_FOLDER_DIA4  AS VARCHAR(1)) AS M_FOLDER_DIA4, 
				CAST(M_FOLDER_DIA5  AS VARCHAR(1)) AS M_FOLDER_DIA5,  CAST(M_FOLDER_DIA6  AS VARCHAR(1)) AS M_FOLDER_DIA6, 
				CAST(M_FOLDER_DIA7  AS VARCHAR(1)) AS M_FOLDER_DIA7,  CAST(M_FOLDER_DIA8  AS VARCHAR(1)) AS M_FOLDER_DIA8, 
				CAST(M_FOLDER_DIA9  AS VARCHAR(1)) AS M_FOLDER_DIA9,  CAST(M_FOLDER_DIA10 AS VARCHAR(1)) AS M_FOLDER_DIA10, 
				CAST(M_FOLDER_DIA11 AS VARCHAR(1)) AS M_FOLDER_DIA11, CAST(M_FOLDER_DIA12 AS VARCHAR(1)) AS M_FOLDER_DIA12, 
				CAST(M_FOLDER_DIA13 AS VARCHAR(1)) AS M_FOLDER_DIA13, CAST(M_FOLDER_DIA14 AS VARCHAR(1)) AS M_FOLDER_DIA14, 
				CAST(M_FOLDER_DIA15 AS VARCHAR(1)) AS M_FOLDER_DIA15, CAST(M_FOLDER_DIA16 AS VARCHAR(1)) AS M_FOLDER_DIA16, 
				CAST(M_FOLDER_DIA17 AS VARCHAR(1)) AS M_FOLDER_DIA17, CAST(M_FOLDER_DIA18 AS VARCHAR(1)) AS M_FOLDER_DIA18, 
				CAST(M_FOLDER_DIA19 AS VARCHAR(1)) AS M_FOLDER_DIA19, CAST(M_FOLDER_DIA20 AS VARCHAR(1)) AS M_FOLDER_DIA20, 
				CAST(M_FOLDER_DIA21 AS VARCHAR(1)) AS M_FOLDER_DIA21, CAST(M_FOLDER_DIA22 AS VARCHAR(1)) AS M_FOLDER_DIA22, 
				CAST(M_FOLDER_DIA23 AS VARCHAR(1)) AS M_FOLDER_DIA23, CAST(M_FOLDER_DIA24 AS VARCHAR(1)) AS M_FOLDER_DIA24, 
				CAST(M_FOLDER_DIA25 AS VARCHAR(1)) AS M_FOLDER_DIA25, CAST(M_FOLDER_DIA26 AS VARCHAR(1)) AS M_FOLDER_DIA26, 
				CAST(M_FOLDER_DIA27 AS VARCHAR(1)) AS M_FOLDER_DIA27, CAST(M_FOLDER_DIA28 AS VARCHAR(1)) AS M_FOLDER_DIA28, 
				CAST(M_FOLDER_DIA29 AS VARCHAR(1)) AS M_FOLDER_DIA29, CAST(M_FOLDER_DIA30 AS VARCHAR(1)) AS M_FOLDER_DIA30, 
				CAST(M_FOLDER_DIA31 AS VARCHAR(1)) AS M_FOLDER_DIA31
			FROM T710_ESTADIS_OFERTA_FOLDER
			WHERE C_SUCU_EMPR =	ISNULL(@C_SUCU_EMPR, C_SUCU_EMPR) 
				AND C_ARTICULO = ISNULL(@C_ARTICULO, C_ARTICULO) 
				AND ((C_ANIO = YEAR(@FechaOfFolDesde) AND C_MES = MONTH(@FechaOfFolDesde)) 
					OR (C_ANIO = YEAR(@FechaOfFolHasta) AND C_MES = MONTH(@FechaOfFolHasta))) 
			) E
		UNPIVOT
			(DIA FOR M_FOLDER_DIA IN (
			M_FOLDER_DIA1, M_FOLDER_DIA2, M_FOLDER_DIA3, M_FOLDER_DIA4, M_FOLDER_DIA5, M_FOLDER_DIA6, M_FOLDER_DIA7, M_FOLDER_DIA8, M_FOLDER_DIA9
			, M_FOLDER_DIA10, M_FOLDER_DIA11, M_FOLDER_DIA12, M_FOLDER_DIA13, M_FOLDER_DIA14, M_FOLDER_DIA15, M_FOLDER_DIA16, M_FOLDER_DIA17
			, M_FOLDER_DIA18, M_FOLDER_DIA19, M_FOLDER_DIA20, M_FOLDER_DIA21, M_FOLDER_DIA22, M_FOLDER_DIA23, M_FOLDER_DIA24, M_FOLDER_DIA25
			, M_FOLDER_DIA26, M_FOLDER_DIA27, M_FOLDER_DIA28, M_FOLDER_DIA29, M_FOLDER_DIA30, M_FOLDER_DIA31 ) 
			) FOL ON YEAR(FechaOfertaYFolder) = FOL.C_ANIO AND MONTH(FechaOfertaYFolder) = FOL.C_MES AND DAY(FechaOfertaYFolder) = SUBSTRING(FOL.M_FOLDER_DIA, 13, LEN(FOL.M_FOLDER_DIA) - 12)
		) AS X

	WHERE S_ELASTICIDAD_DETALLE.C_ARTICULO = X.C_ARTICULO
		AND S_ELASTICIDAD_DETALLE.C_SUCU_EMPR = X.C_SUCU_EMPR
		AND S_ELASTICIDAD_DETALLE.F_DIA = X.DateValue

	IF @@ERROR <> 0 
	    BEGIN
			SET @vchMensaje = 'Error en SQL < UPDATE en S_ELASTICIDAD_DETALLE (FOLDER) > en Stored Procedure SD99_CIERREGRAL_CALCULO_ESTADISTICA_DIAS_REPOSICION'
			RETURN 99
		END


	--////////////////////////////////////////////// INSERTO OFERTA /////////////////////////////////////////////////////////////////////


	UPDATE S_ELASTICIDAD_DETALLE 
	SET M_OFERTA = X.M_OFERTA
	FROM (
		SELECT T.DateValue,
			T.FechaOfertaYFolder, 
			OFERTA.C_SUCU_EMPR, 
			OFERTA.C_ARTICULO, 
			OFERTA.DIA AS M_OFERTA
		FROM
		#TempFechas T
		INNER JOIN 
			(
			SELECT C_ANIO, 
				C_MES, 
				C_SUCU_EMPR, 
				C_ARTICULO, 
				CAST(M_OFERTA_DIA1  AS VARCHAR(1)) AS M_OFERTA_DIA1,  CAST(M_OFERTA_DIA2 AS VARCHAR(1))  AS M_OFERTA_DIA2, 
				CAST(M_OFERTA_DIA3  AS VARCHAR(1)) AS M_OFERTA_DIA3,  CAST(M_OFERTA_DIA4 AS VARCHAR(1))  AS M_OFERTA_DIA4, 
				CAST(M_OFERTA_DIA5  AS VARCHAR(1)) AS M_OFERTA_DIA5,  CAST(M_OFERTA_DIA6 AS VARCHAR(1))  AS M_OFERTA_DIA6, 
				CAST(M_OFERTA_DIA7  AS VARCHAR(1)) AS M_OFERTA_DIA7,  CAST(M_OFERTA_DIA8 AS VARCHAR(1))  AS M_OFERTA_DIA8, 
				CAST(M_OFERTA_DIA9  AS VARCHAR(1)) AS M_OFERTA_DIA9,  CAST(M_OFERTA_DIA10 AS VARCHAR(1)) AS M_OFERTA_DIA10, 
				CAST(M_OFERTA_DIA11 AS VARCHAR(1)) AS M_OFERTA_DIA11, CAST(M_OFERTA_DIA12 AS VARCHAR(1)) AS M_OFERTA_DIA12, 
				CAST(M_OFERTA_DIA13 AS VARCHAR(1)) AS M_OFERTA_DIA13, CAST(M_OFERTA_DIA14 AS VARCHAR(1)) AS M_OFERTA_DIA14, 
				CAST(M_OFERTA_DIA15 AS VARCHAR(1)) AS M_OFERTA_DIA15, CAST(M_OFERTA_DIA16 AS VARCHAR(1)) AS M_OFERTA_DIA16, 
				CAST(M_OFERTA_DIA17 AS VARCHAR(1)) AS M_OFERTA_DIA17, CAST(M_OFERTA_DIA18 AS VARCHAR(1)) AS M_OFERTA_DIA18, 
				CAST(M_OFERTA_DIA19 AS VARCHAR(1)) AS M_OFERTA_DIA19, CAST(M_OFERTA_DIA20 AS VARCHAR(1)) AS M_OFERTA_DIA20, 
				CAST(M_OFERTA_DIA21 AS VARCHAR(1)) AS M_OFERTA_DIA21, CAST(M_OFERTA_DIA22 AS VARCHAR(1)) AS M_OFERTA_DIA22, 
				CAST(M_OFERTA_DIA23 AS VARCHAR(1)) AS M_OFERTA_DIA23, CAST(M_OFERTA_DIA24 AS VARCHAR(1)) AS M_OFERTA_DIA24, 
				CAST(M_OFERTA_DIA25 AS VARCHAR(1)) AS M_OFERTA_DIA25, CAST(M_OFERTA_DIA26 AS VARCHAR(1)) AS M_OFERTA_DIA26, 
				CAST(M_OFERTA_DIA27 AS VARCHAR(1)) AS M_OFERTA_DIA27, CAST(M_OFERTA_DIA28 AS VARCHAR(1)) AS M_OFERTA_DIA28, 
				CAST(M_OFERTA_DIA29 AS VARCHAR(1)) AS M_OFERTA_DIA29, CAST(M_OFERTA_DIA30 AS VARCHAR(1)) AS M_OFERTA_DIA30, 
				CAST(M_OFERTA_DIA31 AS VARCHAR(1)) AS M_OFERTA_DIA31 
			FROM T710_ESTADIS_OFERTA_FOLDER
			WHERE C_SUCU_EMPR =	ISNULL(@C_SUCU_EMPR, C_SUCU_EMPR) 
				AND C_ARTICULO = ISNULL(@C_ARTICULO, C_ARTICULO) 
				AND ((C_ANIO = YEAR(@FechaOfFolDesde) AND C_MES = MONTH(@FechaOfFolDesde)) 
					OR (C_ANIO = YEAR(@FechaOfFolHasta) AND C_MES = MONTH(@FechaOfFolHasta))) 

			) E
		UNPIVOT
			(DIA FOR M_OFERTA_DIA IN (
			M_OFERTA_DIA1, M_OFERTA_DIA2, M_OFERTA_DIA3, M_OFERTA_DIA4, M_OFERTA_DIA5, M_OFERTA_DIA6, M_OFERTA_DIA7, M_OFERTA_DIA8, M_OFERTA_DIA9
			, M_OFERTA_DIA10, M_OFERTA_DIA11, M_OFERTA_DIA12, M_OFERTA_DIA13, M_OFERTA_DIA14, M_OFERTA_DIA15, M_OFERTA_DIA16, M_OFERTA_DIA17
			, M_OFERTA_DIA18, M_OFERTA_DIA19, M_OFERTA_DIA20, M_OFERTA_DIA21, M_OFERTA_DIA22, M_OFERTA_DIA23, M_OFERTA_DIA24, M_OFERTA_DIA25
			, M_OFERTA_DIA26, M_OFERTA_DIA27, M_OFERTA_DIA28, M_OFERTA_DIA29, M_OFERTA_DIA30, M_OFERTA_DIA31 ) 
			) OFERTA ON YEAR(FechaOfertaYFolder) = OFERTA.C_ANIO AND MONTH(FechaOfertaYFolder) = OFERTA.C_MES AND DAY(FechaOfertaYFolder) = SUBSTRING(OFERTA.M_OFERTA_DIA, 13, LEN(OFERTA.M_OFERTA_DIA) - 12)
		) AS X
	WHERE S_ELASTICIDAD_DETALLE.C_ARTICULO = X.C_ARTICULO
		AND S_ELASTICIDAD_DETALLE.C_SUCU_EMPR = X.C_SUCU_EMPR
		AND S_ELASTICIDAD_DETALLE.F_DIA= X.DateValue

	IF @@ERROR <> 0 
	    BEGIN
			SET @vchMensaje = 'Error en SQL < UPDATE en S_ELASTICIDAD_DETALLE (OFERTA) > en Stored Procedure SD99_CIERREGRAL_CALCULO_ESTADISTICA_DIAS_REPOSICION'
			RETURN 99
		END

	PRINT 'HAGO SEPA'
    

	--//////////////////////////////////// INSERTO Ventas //////////////////////////////////////////////////


	UPDATE S_ELASTICIDAD_DETALLE 
	SET Q_VENTA = X.Venta
	FROM (
		SELECT T.DateValue, 
			VENTA.C_ARTICULO, 
			VENTA.C_SUCU_EMPR, 
			VENTA.Venta
		FROM #TempFechas T
		LEFT JOIN (
			SELECT C_SUCU_EMPR, 
				C_ARTICULO, 
				SUBSTRING(Q_DIA, 6, LEN(Q_DIA) - 5) AS DIA, 
				Venta 
			FROM (
				SELECT C_SUCU_EMPR, C_ARTICULO, Q_DIA1, Q_DIA2, Q_DIA3, Q_DIA4, Q_DIA5, Q_DIA6, Q_DIA7, CAST(Q_DIA8 AS DECIMAL(11,3)) AS Q_DIA8, 
					Q_DIA9, Q_DIA10, Q_DIA11, Q_DIA12, Q_DIA13, Q_DIA14, Q_DIA15, Q_DIA16, Q_DIA17, Q_DIA18, Q_DIA19, Q_DIA20, Q_DIA21, Q_DIA22, 
					Q_DIA23, Q_DIA24, Q_DIA25, Q_DIA26, Q_DIA27, Q_DIA28, Q_DIA29, Q_DIA30, Q_DIA31 
				FROM T710_ESTADIS 
				WHERE C_SUCU_EMPR = ISNULL(@C_SUCU_EMPR, C_SUCU_EMPR)
					AND C_ARTICULO = ISNULL(@C_ARTICULO, C_ARTICULO)
				) E
				UNPIVOT
					(Venta FOR Q_DIA IN (
					Q_DIA1, Q_DIA2, Q_DIA3, Q_DIA4, Q_DIA5, Q_DIA6, Q_DIA7, Q_DIA8, Q_DIA9, Q_DIA10, Q_DIA11, Q_DIA12, Q_DIA13, Q_DIA14, Q_DIA15, 
					Q_DIA16, Q_DIA17, Q_DIA18, Q_DIA19, Q_DIA20, Q_DIA21, Q_DIA22, Q_DIA23, Q_DIA24, Q_DIA25, Q_DIA26, Q_DIA27, Q_DIA28, Q_DIA29, 
					Q_DIA30, Q_DIA31 )
					) U 
				) VENTA ON DAY(T.DateValue) = VENTA.DIA
		) AS X
	WHERE S_ELASTICIDAD_DETALLE.C_ARTICULO = X.C_ARTICULO
		AND S_ELASTICIDAD_DETALLE.C_SUCU_EMPR = X.C_SUCU_EMPR
		AND S_ELASTICIDAD_DETALLE.F_DIA = X.DateValue


	IF @@ERROR <> 0 
	    BEGIN
			SET @vchMensaje = 'Error en SQL < UPDATE en S_ELASTICIDAD_DETALLE (VENTA) > en Stored Procedure SD99_CIERREGRAL_CALCULO_ESTADISTICA_DIAS_REPOSICION'
			RETURN 99
		END

	--/////////////////////////////////// INSERTO STOCK ////////////////////////////////////////////////


	UPDATE S_ELASTICIDAD_DETALLE 
	SET Q_STOCK = X.STOCK 
	FROM (
		SELECT T.DateValue,
			C_SUCU_EMPR, 
			C_ARTICULO, 
			STOCK
		FROM #TempFechas T
		INNER JOIN (
			SELECT C_SUCU_EMPR, C_ARTICULO, C_ANIO, C_MES, Q_DIA1, Q_DIA2, Q_DIA3, Q_DIA4, Q_DIA5, Q_DIA6, Q_DIA7, 
				CAST(Q_DIA8 AS DECIMAL(11,3)) AS Q_DIA8, Q_DIA9, Q_DIA10, Q_DIA11, Q_DIA12, Q_DIA13, Q_DIA14, Q_DIA15, 
				Q_DIA16, Q_DIA17, Q_DIA18, Q_DIA19, Q_DIA20, Q_DIA21, Q_DIA22, Q_DIA23, Q_DIA24, Q_DIA25, Q_DIA26, 
				Q_DIA27, Q_DIA28, Q_DIA29, Q_DIA30, Q_DIA31 
			FROM T710_ESTADIS_STOCK
			WHERE C_SUCU_EMPR = ISNULL(@C_SUCU_EMPR, C_SUCU_EMPR) 
				AND C_ARTICULO = ISNULL(@C_ARTICULO, C_ARTICULO) 
				AND ((C_ANIO = YEAR(@FechaStockDesde) AND C_MES = MONTH(@FechaStockDesde)) 
					OR (C_ANIO = YEAR(@FechaStockHasta) AND C_MES = MONTH(@FechaStockHasta))) 
				) E
			UNPIVOT
				(STOCK FOR Q_DIA IN (
				Q_DIA1, Q_DIA2, Q_DIA3, Q_DIA4, Q_DIA5, Q_DIA6, Q_DIA7, Q_DIA8, Q_DIA9, Q_DIA10, Q_DIA11, Q_DIA12, Q_DIA13, Q_DIA14, Q_DIA15, 
				Q_DIA16, Q_DIA17, Q_DIA18, Q_DIA19, Q_DIA20, Q_DIA21, Q_DIA22, Q_DIA23, Q_DIA24, Q_DIA25, Q_DIA26, Q_DIA27, Q_DIA28, Q_DIA29, 
				Q_DIA30, Q_DIA31 )
				) ZZ ON YEAR(FechaStock) = ZZ.C_ANIO AND MONTH(FechaStock) = ZZ.C_MES AND DAY(FechaStock) = SUBSTRING(Q_DIA, 6, LEN(Q_DIA) - 5) 
		) AS X
	WHERE S_ELASTICIDAD_DETALLE.C_ARTICULO = X.C_ARTICULO
		AND S_ELASTICIDAD_DETALLE.C_SUCU_EMPR = X.C_SUCU_EMPR
		AND S_ELASTICIDAD_DETALLE.F_DIA = X.DateValue
		


	IF @@ERROR <> 0 
	    BEGIN
			SET @vchMensaje = 'Error en SQL < UPDATE en S_ELASTICIDAD_DETALLE (STOCK) > en Stored Procedure SD99_CIERREGRAL_CALCULO_ESTADISTICA_DIAS_REPOSICION'
			RETURN 99
		END

--//////  INSERTO SEPA
	UPDATE S_ELASTICIDAD_DETALLE 
	SET M_SEPA = X.M_SEPA
	FROM (
		SELECT T.DateValue,
			T.FechaOfertaYFolder, 
			SEPA.C_SUCU_EMPR, 
			SEPA.C_ARTICULO, 
			SEPA.DIA AS M_SEPA
		FROM
		#TempFechas T
		INNER JOIN 
			(
			SELECT C_ANIO, 
				C_MES, 
				C_SUCU_EMPR, 
				C_ARTICULO, 
				CAST(M_SEPA_DIA1  AS VARCHAR(1)) AS M_SEPA_DIA1,  CAST(M_SEPA_DIA2 AS VARCHAR(1))  AS M_SEPA_DIA2, 
				CAST(M_SEPA_DIA3  AS VARCHAR(1)) AS M_SEPA_DIA3,  CAST(M_SEPA_DIA4 AS VARCHAR(1))  AS M_SEPA_DIA4, 
				CAST(M_SEPA_DIA5  AS VARCHAR(1)) AS M_SEPA_DIA5,  CAST(M_SEPA_DIA6 AS VARCHAR(1))  AS M_SEPA_DIA6, 
				CAST(M_SEPA_DIA7  AS VARCHAR(1)) AS M_SEPA_DIA7,  CAST(M_SEPA_DIA8 AS VARCHAR(1))  AS M_SEPA_DIA8, 
				CAST(M_SEPA_DIA9  AS VARCHAR(1)) AS M_SEPA_DIA9,  CAST(M_SEPA_DIA10 AS VARCHAR(1)) AS M_SEPA_DIA10, 
				CAST(M_SEPA_DIA11 AS VARCHAR(1)) AS M_SEPA_DIA11, CAST(M_SEPA_DIA12 AS VARCHAR(1)) AS M_SEPA_DIA12, 
				CAST(M_SEPA_DIA13 AS VARCHAR(1)) AS M_SEPA_DIA13, CAST(M_SEPA_DIA14 AS VARCHAR(1)) AS M_SEPA_DIA14, 
				CAST(M_SEPA_DIA15 AS VARCHAR(1)) AS M_SEPA_DIA15, CAST(M_SEPA_DIA16 AS VARCHAR(1)) AS M_SEPA_DIA16, 
				CAST(M_SEPA_DIA17 AS VARCHAR(1)) AS M_SEPA_DIA17, CAST(M_SEPA_DIA18 AS VARCHAR(1)) AS M_SEPA_DIA18, 
				CAST(M_SEPA_DIA19 AS VARCHAR(1)) AS M_SEPA_DIA19, CAST(M_SEPA_DIA20 AS VARCHAR(1)) AS M_SEPA_DIA20, 
				CAST(M_SEPA_DIA21 AS VARCHAR(1)) AS M_SEPA_DIA21, CAST(M_SEPA_DIA22 AS VARCHAR(1)) AS M_SEPA_DIA22, 
				CAST(M_SEPA_DIA23 AS VARCHAR(1)) AS M_SEPA_DIA23, CAST(M_SEPA_DIA24 AS VARCHAR(1)) AS M_SEPA_DIA24, 
				CAST(M_SEPA_DIA25 AS VARCHAR(1)) AS M_SEPA_DIA25, CAST(M_SEPA_DIA26 AS VARCHAR(1)) AS M_SEPA_DIA26, 
				CAST(M_SEPA_DIA27 AS VARCHAR(1)) AS M_SEPA_DIA27, CAST(M_SEPA_DIA28 AS VARCHAR(1)) AS M_SEPA_DIA28, 
				CAST(M_SEPA_DIA29 AS VARCHAR(1)) AS M_SEPA_DIA29, CAST(M_SEPA_DIA30 AS VARCHAR(1)) AS M_SEPA_DIA30, 
				CAST(M_SEPA_DIA31 AS VARCHAR(1)) AS M_SEPA_DIA31 
			FROM T710_ESTADIS_SEPA
			WHERE C_SUCU_EMPR =	ISNULL(@C_SUCU_EMPR, C_SUCU_EMPR) 
				AND C_ARTICULO = ISNULL(@C_ARTICULO, C_ARTICULO) 
				AND ((C_ANIO = YEAR(@FechaOfFolDesde) AND C_MES = MONTH(@FechaOfFolDesde)) 
					OR (C_ANIO = YEAR(@FechaOfFolHasta) AND C_MES = MONTH(@FechaOfFolHasta))) 

			) E
		UNPIVOT
			(DIA FOR M_SEPA_DIA IN (
			M_SEPA_DIA1, M_SEPA_DIA2, M_SEPA_DIA3, M_SEPA_DIA4, M_SEPA_DIA5, M_SEPA_DIA6, M_SEPA_DIA7, M_SEPA_DIA8, M_SEPA_DIA9
			, M_SEPA_DIA10, M_SEPA_DIA11, M_SEPA_DIA12, M_SEPA_DIA13, M_SEPA_DIA14, M_SEPA_DIA15, M_SEPA_DIA16, M_SEPA_DIA17
			, M_SEPA_DIA18, M_SEPA_DIA19, M_SEPA_DIA20, M_SEPA_DIA21, M_SEPA_DIA22, M_SEPA_DIA23, M_SEPA_DIA24, M_SEPA_DIA25
			, M_SEPA_DIA26, M_SEPA_DIA27, M_SEPA_DIA28, M_SEPA_DIA29, M_SEPA_DIA30, M_SEPA_DIA31 ) 
			) SEPA ON YEAR(FechaOfertaYFolder) = SEPA.C_ANIO AND MONTH(FechaOfertaYFolder) = SEPA.C_MES AND DAY(FechaOfertaYFolder) = SUBSTRING(SEPA.M_SEPA_DIA, 11, LEN(SEPA.M_SEPA_DIA) - 10)
		) AS X
	WHERE S_ELASTICIDAD_DETALLE.C_ARTICULO = X.C_ARTICULO
		AND S_ELASTICIDAD_DETALLE.C_SUCU_EMPR = X.C_SUCU_EMPR
		AND S_ELASTICIDAD_DETALLE.F_DIA= X.DateValue

	IF @@ERROR <> 0 
	    BEGIN
			SET @vchMensaje = 'Error en SQL < UPDATE en S_ELASTICIDAD_DETALLE (SEPA) > en Stored Procedure SD99_CIERREGRAL_CALCULO_ESTADISTICA_DIAS_REPOSICION'
			RETURN 99
		END

		PRINT 'TERMINE SEPA'
    --//// FIN AGREGADO MARCA SEPA




<<<<
AS 
/*
Genera HEADER con los campos
Transforma en STRING todos los campos
Trae la estadísticas de ventas diaria por sucursal (LOCAL/PLU/FECHA) 1,5 M de registros
Para Entrenar Modelo, Voy a generar un SUB_SET de datos

Rango PLU
Rango FECHAS
*/
BEGIN 
	SET NOCOUNT ON;

	DECLARE @Fecha_Ant DATETIME;
	SET @Fecha_Ant = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE);

	SELECT 'F_DIA','C_SUCU_EMPR','C_ARTICULO','M_DOMINGO','M_FOLDER','M_OFERTA','Q_VENTA','Q_STOCK','M_SEPA'
	UNION ALL
	
	SELECT CONVERT(varchar,[F_DIA],121) 
      ,CONVERT(varchar,[C_SUCU_EMPR])
      ,CONVERT(varchar,[C_ARTICULO])
      ,CONVERT(varchar,[M_DOMINGO])
      ,CONVERT(varchar,[M_FOLDER])
      ,CONVERT(varchar,[M_OFERTA])
      ,CONVERT(varchar,[Q_VENTA])
      ,CONVERT(varchar,[Q_STOCK])
      ,CONVERT(varchar,[M_SEPA])
	  FROM [DIARCOP001].[DiarcoP].[dbo].[S_ELASTICIDAD_DETALLE]
	  WHERE [F_DIA] = @Fecha_Ant
END;
		
GO


