USE [data-sync]
GO

TRUNCATE TABLE [dbo].[M_10_PROVEEDORES]
GO

INSERT INTO [dbo].[M_10_PROVEEDORES]
           ([C_PROVEEDOR],[C_TIPO_PROVEEDOR],[C_TIPO_PROVEEDOR_DIARCO],[C_CUIT],[N_PROVEEDOR],[C_CLIENTE],[F_ALTA],[F_BAJA],[F_MODIF],[M_ACTIVO]
			,[C_LINEA_PRODUCTO],[C_EANEDI],[N_VENDEDOR],[D_CHEQ_ALAORDEN],[N_ENCARG_COMPRA],[C_USUARIO],[C_TERMINAL],[C_PLAZO_ENTREGA1],[M_ATEN_CLIE_LUN],[M_ATEN_CLIE_MAR]
			,[M_ATEN_CLIE_MIE],[M_ATEN_CLIE_JUE],[M_ATEN_CLIE_VIE],[M_ATEN_CLIE_SAB],[M_ATEN_CLIE_DOM],[I_ENVASE],[M_BAJA],[M_AGENTE_RET_IVA],[M_COMPRA_PALETIZADO],[C_ORIGEN_PROVEEDOR]
			,[N_ESTADO],[N_PAIS],[N_CIUDAD],[U_DIAS_TOPE_PARA_AGENDA],[U_DIAS_TOPE_PARA_INGRESO_AGENDA],[M_ATEN_PROV_LUN],[M_ATEN_PROV_MAR],[M_ATEN_PROV_MIE],[M_ATEN_PROV_JUE]
			,[M_ATEN_PROV_VIE],[M_ATEN_PROV_SAB],[M_ATEN_PROV_DOM],[C_PERIODO_ATENCION_AGENDA],[M_COBRA_PERCEP_SEGHIG_CORDOBA],[M_COBRA_PERCEP_SEGHIG_MISIONES],[M_INSCRIPTO_SEG_HIG_POSADAS]
           ,[F_PROC])
    
	SELECT [C_PROVEEDOR],[C_TIPO_PROVEEDOR],[C_TIPO_PROVEEDOR_DIARCO],[C_CUIT],[N_PROVEEDOR],[C_CLIENTE],[F_ALTA],[F_BAJA],[F_MODIF],[M_ACTIVO],[C_LINEA_PRODUCTO]
		,[C_EANEDI],[N_VENDEDOR],[D_CHEQ_ALAORDEN],[N_ENCARG_COMPRA],[C_USUARIO],[C_TERMINAL],[C_PLAZO_ENTREGA1],[M_ATEN_CLIE_LUN],[M_ATEN_CLIE_MAR],[M_ATEN_CLIE_MIE],[M_ATEN_CLIE_JUE]
		,[M_ATEN_CLIE_VIE],[M_ATEN_CLIE_SAB],[M_ATEN_CLIE_DOM],[I_ENVASE],[M_BAJA],[M_AGENTE_RET_IVA],[M_COMPRA_PALETIZADO],[C_ORIGEN_PROVEEDOR],[N_ESTADO],[N_PAIS],[N_CIUDAD]
		,[U_DIAS_TOPE_PARA_AGENDA],[U_DIAS_TOPE_PARA_INGRESO_AGENDA],[M_ATEN_PROV_LUN],[M_ATEN_PROV_MAR],[M_ATEN_PROV_MIE],[M_ATEN_PROV_JUE],[M_ATEN_PROV_VIE],[M_ATEN_PROV_SAB]
		,[M_ATEN_PROV_DOM],[C_PERIODO_ATENCION_AGENDA],[M_COBRA_PERCEP_SEGHIG_CORDOBA],[M_COBRA_PERCEP_SEGHIG_MISIONES],[M_INSCRIPTO_SEG_HIG_POSADAS]
		,GETDATE() as [F_PROC]

  FROM [DIARCOP001].[DiarcoP].[dbo].[T020_PROVEEDOR]

  ORDER BY C_PROVEEDOR
GO


