
SELECT DISTINCT *  
FROM [repl].[T710_ESTADIS_STOCK] S  
LEFT JOIN [repl].[T050_ARTICULOS] A  
    ON S.C_ARTICULO = A.C_ARTICULO  
WHERE S.C_ANIO * 100 + S.C_MES >= 
    CONVERT(INT, FORMAT(DATEADD(MONTH, -1, GETDATE()), 'yyyyMM'))  
AND A.C_PROVEEDOR_PRIMARIO = 20;  
GO
----- # BASE de STOCK
SELECT TOP 100
  	 S.[C_ANIO],S.[C_MES],S.[C_SUCU_EMPR],A.C_PROVEEDOR_PRIMARIO,S.[C_ARTICULO],S.[Q_DIA1],S.[Q_DIA2],S.[Q_DIA3],S.[Q_DIA4],S.[Q_DIA5],S.[Q_DIA6],S.[Q_DIA7],S.[Q_DIA8],S.[Q_DIA9]
	,S.[Q_DIA10],S.[Q_DIA11],S.[Q_DIA12],S.[Q_DIA13],S.[Q_DIA14],S.[Q_DIA15],S.[Q_DIA16],S.[Q_DIA17],S.[Q_DIA18],S.[Q_DIA19]
	,S.[Q_DIA20],S.[Q_DIA21],S.[Q_DIA22],S.[Q_DIA23],S.[Q_DIA24],S.[Q_DIA25],S.[Q_DIA26],S.[Q_DIA27],S.[Q_DIA28],S.[Q_DIA29]
	,S.[Q_DIA30],S.[Q_DIA31]  
FROM [repl].[T710_ESTADIS_STOCK] S
LEFT JOIN [repl].[T050_ARTICULOS] A  
    ON S.C_ARTICULO = A.C_ARTICULO  
WHERE C_ANIO = 2025
AND A.C_PROVEEDOR_PRIMARIO IN ( 20, 1074); 

------- # BASE DE OFERTAS
SELECT  
    O.C_ANIO, O.C_MES, O.C_SUCU_EMPR, A.C_PROVEEDOR_PRIMARIO, O.C_ARTICULO,
    O.M_OFERTA_DIA1, O.M_OFERTA_DIA2, O.M_OFERTA_DIA3, O.M_OFERTA_DIA4, O.M_OFERTA_DIA5, 
    O.M_OFERTA_DIA6, O.M_OFERTA_DIA7, O.M_OFERTA_DIA8, O.M_OFERTA_DIA9, O.M_OFERTA_DIA10,
    O.M_OFERTA_DIA11, O.M_OFERTA_DIA12, O.M_OFERTA_DIA13, O.M_OFERTA_DIA14, O.M_OFERTA_DIA15, 
    O.M_OFERTA_DIA16, O.M_OFERTA_DIA17, O.M_OFERTA_DIA18, O.M_OFERTA_DIA19, O.M_OFERTA_DIA20,
    O.M_OFERTA_DIA21, O.M_OFERTA_DIA22, O.M_OFERTA_DIA23, O.M_OFERTA_DIA24, O.M_OFERTA_DIA25, 
    O.M_OFERTA_DIA26, O.M_OFERTA_DIA27, O.M_OFERTA_DIA28, O.M_OFERTA_DIA29, O.M_OFERTA_DIA30,
    O.M_OFERTA_DIA31
FROM [repl].[T710_ESTADIS_OFERTA_FOLDER] O
LEFT JOIN [repl].[T050_ARTICULOS] A ON O.C_ARTICULO = A.C_ARTICULO
WHERE C_ANIO = 2025
AND A.C_PROVEEDOR_PRIMARIO IN ( 20, 1074); ;
