SELECT TOP (1000) [C_SUCU_EMPR]
      ,[N_SUCURSAL]
      ,[N_SUCURSAL_ABREV]
      ,[N_SUCURSAL_ABREV2]
      ,[N_SUCURSAL_ABREV3]
      ,[N_CALLE]
      ,[N_LOCALIDAD]
      ,[C_POSTAL_INM]
      ,[C_PROVINCIA_SUCU]
      ,[C_ZONA]
      ,[C_ZONA_REGIONAL]
      ,[CLUSTER_LOG]
      ,[C_FORMATO]
      ,[FORMATO]
      ,[M_BAJA]
  FROM [data-sync].[dbo].[T_100_SUCURSALES]

  UPDATE [data-sync].[dbo].[T_100_SUCURSALES]
SET 
    C_SUCU_EMPR = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(C_SUCU_EMPR, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    N_SUCURSAL = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(N_SUCURSAL, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    N_SUCURSAL_ABREV = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(N_SUCURSAL_ABREV, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    N_SUCURSAL_ABREV2 = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(N_SUCURSAL_ABREV2, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    N_SUCURSAL_ABREV3 = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(N_SUCURSAL_ABREV3, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    N_CALLE = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(N_CALLE, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    N_LOCALIDAD = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(N_LOCALIDAD, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    C_POSTAL_INM = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(C_POSTAL_INM, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    C_PROVINCIA_SUCU = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(C_PROVINCIA_SUCU, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    C_ZONA = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(C_ZONA, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    C_ZONA_REGIONAL = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(C_ZONA_REGIONAL, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    CLUSTER_LOG = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLUSTER_LOG, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    C_FORMATO = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(C_FORMATO, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    FORMATO = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(FORMATO, CHAR(9), ''), CHAR(13), ''), CHAR(10), ''))),
    M_BAJA = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(M_BAJA, CHAR(9), ''), CHAR(13), ''), CHAR(10), '')));
