
  SELECT 
		[C_PROVEEDOR_PRIMARIO], C_COMPRADOR
		,T1.C_ARTICULO, T1.N_ARTICULO, T1.Q_PESO_UNIT_ART, T1.M_VENDE_POR_PESO, T1.C_UNIDAD_MEDIDA
			,T2.D_CODIGO, C_CLASIFICACION_COMPRA
		      ,C_EAN,  C_DUN14
			        ,T3.[Q_FACTOR_PROVEEDOR]
      ,T3.[U_PISO_PALETIZADO]
      ,T3.[U_ALTURA_PALETIZADO]
	  ,'en bultos' as BULTOS_COMPRA_MINIMA
	  ,'en cm.' as ALTO_BULTO
	  , 'en cm.' as ANCHO_BULTO
	  , ' en Kg.' as PESO_BULTO
	  , 'S o N' as PALLET_MONOPRODUCTO
	  	  
	  ,[M_A_DAR_DE_BAJA]
	  ,[F_BAJA]

  FROM [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS] T1,
	  [DIARCOP001].[DiarcoP].[dbo].[T001_TABLA_CODIGO] T2,
	  [DIARCOP001].[DiarcoP].[dbo].[T052_ARTICULOS_PROVEEDOR] T3
WHERE	  T1.C_UNIDAD_MEDIDA = T2.C_CODIGO_TABLA
		AND T3.C_ARTICULO = T1.C_ARTICULO
		AND T3.C_PROVEEDOR = T1.C_PROVEEDOR_PRIMARIO
AND	  T2.C_TABLA = 79

AND [C_PROVEEDOR_PRIMARIO] IN (2676, 190, 6363, 3835)

ORDER BY C_PROVEEDOR_PRIMARIO, C_ARTICULO
GO