SELECT TOP (1000) [C_OC]
      ,[F_EMISION]
      ,[U_PREFIJO_OC]
      ,[U_SUFIJO_OC]
      ,[C_PROVEEDOR]
      ,[C_SUCU_COMPRA]
      ,[C_SUCU_DESTINO]
      ,[C_ARTICULO]
	  ,[M_CUMPLIDA_PARCIAL]

      ,[STOCK_UNIDADES]
      ,[PEDIDO_UNIDADES]
	  ,[Q_UNID_CUMPLIDAS]
      ,[PENDIENTE_UNIDADES]
      ,[STOCK_VALORIZADO]

  FROM [data-sync].[dbo].[T_OC_DETALLE_EXT]
 --  WHERE M_CUMPLIDA_PARCIAL <> 'N'

UPDATE T
SET PENDIENTE_UNIDADES = T.Q_BULTOS_EMPR_PED * T.Q_FACTOR_EMPR_PED - T.Q_UNID_CUMPLIDAS
FROM dbo.T_OC_DETALLE_EXT AS T
WHERE T.M_CUMPLIDA_PARCIAL <> 'N' -- Condición para excluir registros
AND EXISTS (
    SELECT 1
    FROM dbo.T_OC_DETALLE_EXT AS Sub
    WHERE Sub.C_ARTICULO = T.C_ARTICULO -- Mismo artículo
      AND Sub.C_SUCU_DESTINO = T.C_SUCU_DESTINO -- Misma sucursal
      AND Sub.F_EMISION < T.F_EMISION -- Fecha de emisión menor
      AND Sub.M_CUMPLIDA_PARCIAL <> 'N' -- Condición adicional para el subconjunto
);


--- CONSULTaR REGISTROS AFECtAROD

SELECT *
FROM dbo.T_OC_DETALLE_EXT AS T
WHERE T.M_CUMPLIDA_PARCIAL <> 'N'
AND EXISTS (
    SELECT 1
    FROM dbo.T_OC_DETALLE_EXT AS Sub
    WHERE Sub.C_ARTICULO = T.C_ARTICULO
      AND Sub.C_SUCU_DESTINO = T.C_SUCU_DESTINO
      AND Sub.F_EMISION < T.F_EMISION
      AND Sub.M_CUMPLIDA_PARCIAL <> 'N'
);
