/*** Este Script trabaja sobre la base de datos de  DIARCO PRODUCCIÓN       ***/
/**** Generar Tabla FULL con Precios Diarios para Elasticidad de la Demanda ***/

/*** POBLAR TABLA DE INPUT DESDE ORIGEN *** [dbo].[T_ESTADISTICA_PRECIOS]  ****/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_ESTADISTICA_PRECIOS]') AND type in (N'U'))
DROP TABLE [dbo].[T_ESTADISTICA_PRECIOS]
GO

DECLARE @StartYear AS INT
DECLARE @StartMonth AS INT
DECLARE @EndYear AS INT
DECLARE @EndMonth AS INT

SET @StartYear = 2024
SET @StartMonth = 11;
SET @EndYear = 2024;
SET @EndMonth = 12

--- POBLAREMOS DE A UN MES PORQUE SON 3 MILLONES DE REGISTROS POR MES.
SELECT *
  INTO T_ESTADISTICA_PRECIOS
  FROM [DIARCOP001-BK].[DiarcoP].[dbo].[T710_ESTADIS_PRECIOS]
  WHERE C_ANIO = @StartYear  AND C_MES = @StartMonth
GO

--- SELECT COUNT(*)   FROM [DIARCOP001-BK].[DiarcoP].[dbo].[T710_ESTADIS_PRECIOS] WHERE C_ANIO = 2024 

DECLARE @StartYear AS INT
DECLARE @StartMonth AS INT
DECLARE @EndYear AS INT
DECLARE @EndMonth AS INT

SET @StartYear = 2024
SET @StartMonth = 11;
SET @EndYear = 2024;
SET @EndMonth = 12

;WITH BaseData AS (
    SELECT 
        C_MES,
        C_ANIO,
        C_ARTICULO,
        C_SUCU_EMPR,
        Dia = CAST(SUBSTRING(COLUMNA, LEN(COLUMNA) - CHARINDEX('_', REVERSE(COLUMNA)) + 2, LEN(COLUMNA)) AS INT),
        Tipo_Precio = CASE 
            WHEN COLUMNA LIKE 'I_PRECIO_VTA%' THEN 'PRECIO_VTA'
            WHEN COLUMNA LIKE 'I_COSTO_ESTADISTICO%' THEN 'COSTO_ESTADISTICO'
            WHEN COLUMNA LIKE 'I_COSTO_PP%' THEN 'COSTO_PP'
            WHEN COLUMNA LIKE 'I_COSTO_PARTE_ULTIMO_INGRESO%' THEN 'COSTO_PARTE_ULTIMO_INGRESO'
            WHEN COLUMNA LIKE 'I_COSTO_COMPRA_ULTIMO_INGRESO%' THEN 'COSTO_COMPRA_ULTIMO_INGRESO'
        END,
        Valor
    FROM 
        (SELECT 
            C_MES,
            C_ANIO,
            C_ARTICULO,
            C_SUCU_EMPR
			,[I_PRECIO_VTA_1],[I_PRECIO_VTA_2],[I_PRECIO_VTA_3],[I_PRECIO_VTA_4],[I_PRECIO_VTA_5],[I_PRECIO_VTA_6],[I_PRECIO_VTA_7],[I_PRECIO_VTA_8],[I_PRECIO_VTA_9]
			,[I_PRECIO_VTA_10],[I_PRECIO_VTA_11],[I_PRECIO_VTA_12],[I_PRECIO_VTA_13],[I_PRECIO_VTA_14],[I_PRECIO_VTA_15],[I_PRECIO_VTA_16],[I_PRECIO_VTA_17],[I_PRECIO_VTA_18],[I_PRECIO_VTA_19]
			,[I_PRECIO_VTA_20],[I_PRECIO_VTA_21],[I_PRECIO_VTA_22],[I_PRECIO_VTA_23],[I_PRECIO_VTA_24],[I_PRECIO_VTA_25],[I_PRECIO_VTA_26],[I_PRECIO_VTA_27],[I_PRECIO_VTA_28],[I_PRECIO_VTA_29]
			,[I_PRECIO_VTA_30],[I_PRECIO_VTA_31]
			,[I_COSTO_ESTADISTICO_1],[I_COSTO_ESTADISTICO_2],[I_COSTO_ESTADISTICO_3],[I_COSTO_ESTADISTICO_4],[I_COSTO_ESTADISTICO_5],[I_COSTO_ESTADISTICO_6],[I_COSTO_ESTADISTICO_7],[I_COSTO_ESTADISTICO_8],[I_COSTO_ESTADISTICO_9]
			,[I_COSTO_ESTADISTICO_10],[I_COSTO_ESTADISTICO_11],[I_COSTO_ESTADISTICO_12],[I_COSTO_ESTADISTICO_13],[I_COSTO_ESTADISTICO_14],[I_COSTO_ESTADISTICO_15],[I_COSTO_ESTADISTICO_16],[I_COSTO_ESTADISTICO_17],[I_COSTO_ESTADISTICO_18],[I_COSTO_ESTADISTICO_19]
			,[I_COSTO_ESTADISTICO_20],[I_COSTO_ESTADISTICO_21],[I_COSTO_ESTADISTICO_22],[I_COSTO_ESTADISTICO_23],[I_COSTO_ESTADISTICO_24],[I_COSTO_ESTADISTICO_25],[I_COSTO_ESTADISTICO_26],[I_COSTO_ESTADISTICO_27],[I_COSTO_ESTADISTICO_28],[I_COSTO_ESTADISTICO_29]
			,[I_COSTO_ESTADISTICO_30],[I_COSTO_ESTADISTICO_31]
			,[I_COSTO_PP_1],[I_COSTO_PP_2],[I_COSTO_PP_3],[I_COSTO_PP_4],[I_COSTO_PP_5],[I_COSTO_PP_6],[I_COSTO_PP_7],[I_COSTO_PP_8],[I_COSTO_PP_9]
			,[I_COSTO_PP_10],[I_COSTO_PP_11],[I_COSTO_PP_12],[I_COSTO_PP_13],[I_COSTO_PP_14],[I_COSTO_PP_15],[I_COSTO_PP_16],[I_COSTO_PP_17],[I_COSTO_PP_18],[I_COSTO_PP_19]
			,[I_COSTO_PP_20],[I_COSTO_PP_21],[I_COSTO_PP_22],[I_COSTO_PP_23],[I_COSTO_PP_24],[I_COSTO_PP_25],[I_COSTO_PP_26],[I_COSTO_PP_27],[I_COSTO_PP_28],[I_COSTO_PP_29]
			,[I_COSTO_PP_30],[I_COSTO_PP_31]
			,[I_COSTO_PARTE_ULTIMO_INGRESO_1],[I_COSTO_PARTE_ULTIMO_INGRESO_2],[I_COSTO_PARTE_ULTIMO_INGRESO_3],[I_COSTO_PARTE_ULTIMO_INGRESO_4],[I_COSTO_PARTE_ULTIMO_INGRESO_5],[I_COSTO_PARTE_ULTIMO_INGRESO_6],[I_COSTO_PARTE_ULTIMO_INGRESO_7],[I_COSTO_PARTE_ULTIMO_INGRESO_8],[I_COSTO_PARTE_ULTIMO_INGRESO_9]
			,[I_COSTO_PARTE_ULTIMO_INGRESO_10],[I_COSTO_PARTE_ULTIMO_INGRESO_11],[I_COSTO_PARTE_ULTIMO_INGRESO_12],[I_COSTO_PARTE_ULTIMO_INGRESO_13],[I_COSTO_PARTE_ULTIMO_INGRESO_14],[I_COSTO_PARTE_ULTIMO_INGRESO_15],[I_COSTO_PARTE_ULTIMO_INGRESO_16],[I_COSTO_PARTE_ULTIMO_INGRESO_17],[I_COSTO_PARTE_ULTIMO_INGRESO_18],[I_COSTO_PARTE_ULTIMO_INGRESO_19]
			,[I_COSTO_PARTE_ULTIMO_INGRESO_20],[I_COSTO_PARTE_ULTIMO_INGRESO_21],[I_COSTO_PARTE_ULTIMO_INGRESO_22],[I_COSTO_PARTE_ULTIMO_INGRESO_23],[I_COSTO_PARTE_ULTIMO_INGRESO_24],[I_COSTO_PARTE_ULTIMO_INGRESO_25],[I_COSTO_PARTE_ULTIMO_INGRESO_26],[I_COSTO_PARTE_ULTIMO_INGRESO_27],[I_COSTO_PARTE_ULTIMO_INGRESO_28],[I_COSTO_PARTE_ULTIMO_INGRESO_29]
			,[I_COSTO_PARTE_ULTIMO_INGRESO_30],[I_COSTO_PARTE_ULTIMO_INGRESO_31]
			,[I_COSTO_COMPRA_ULTIMO_INGRESO_1],[I_COSTO_COMPRA_ULTIMO_INGRESO_2],[I_COSTO_COMPRA_ULTIMO_INGRESO_3],[I_COSTO_COMPRA_ULTIMO_INGRESO_4],[I_COSTO_COMPRA_ULTIMO_INGRESO_5],[I_COSTO_COMPRA_ULTIMO_INGRESO_6],[I_COSTO_COMPRA_ULTIMO_INGRESO_7],[I_COSTO_COMPRA_ULTIMO_INGRESO_8],[I_COSTO_COMPRA_ULTIMO_INGRESO_9]
			,[I_COSTO_COMPRA_ULTIMO_INGRESO_10],[I_COSTO_COMPRA_ULTIMO_INGRESO_11],[I_COSTO_COMPRA_ULTIMO_INGRESO_12],[I_COSTO_COMPRA_ULTIMO_INGRESO_13],[I_COSTO_COMPRA_ULTIMO_INGRESO_14],[I_COSTO_COMPRA_ULTIMO_INGRESO_15],[I_COSTO_COMPRA_ULTIMO_INGRESO_16],[I_COSTO_COMPRA_ULTIMO_INGRESO_17],[I_COSTO_COMPRA_ULTIMO_INGRESO_18],[I_COSTO_COMPRA_ULTIMO_INGRESO_19]
			,[I_COSTO_COMPRA_ULTIMO_INGRESO_20],[I_COSTO_COMPRA_ULTIMO_INGRESO_21],[I_COSTO_COMPRA_ULTIMO_INGRESO_22],[I_COSTO_COMPRA_ULTIMO_INGRESO_23],[I_COSTO_COMPRA_ULTIMO_INGRESO_24],[I_COSTO_COMPRA_ULTIMO_INGRESO_25],[I_COSTO_COMPRA_ULTIMO_INGRESO_26],[I_COSTO_COMPRA_ULTIMO_INGRESO_27],[I_COSTO_COMPRA_ULTIMO_INGRESO_28],[I_COSTO_COMPRA_ULTIMO_INGRESO_29]
			,[I_COSTO_COMPRA_ULTIMO_INGRESO_30],[I_COSTO_COMPRA_ULTIMO_INGRESO_31]
        FROM [data-sync].[dbo].[T_ESTADISTICA_PRECIOS]
        WHERE 
            (C_ANIO * 100 + C_MES) BETWEEN (@StartYear * 100 + @StartMonth) AND (@EndYear * 100 + @EndMonth)
        ) AS SourceTable
    UNPIVOT
        (Valor FOR COLUMNA IN 
            ([I_PRECIO_VTA_1],[I_PRECIO_VTA_2],[I_PRECIO_VTA_3],[I_PRECIO_VTA_4],[I_PRECIO_VTA_5],[I_PRECIO_VTA_6],[I_PRECIO_VTA_7],[I_PRECIO_VTA_8],[I_PRECIO_VTA_9]
			,[I_PRECIO_VTA_10],[I_PRECIO_VTA_11],[I_PRECIO_VTA_12],[I_PRECIO_VTA_13],[I_PRECIO_VTA_14],[I_PRECIO_VTA_15],[I_PRECIO_VTA_16],[I_PRECIO_VTA_17],[I_PRECIO_VTA_18],[I_PRECIO_VTA_19]
			,[I_PRECIO_VTA_20],[I_PRECIO_VTA_21],[I_PRECIO_VTA_22],[I_PRECIO_VTA_23],[I_PRECIO_VTA_24],[I_PRECIO_VTA_25],[I_PRECIO_VTA_26],[I_PRECIO_VTA_27],[I_PRECIO_VTA_28],[I_PRECIO_VTA_29]
			,[I_PRECIO_VTA_30],[I_PRECIO_VTA_31]
			,[I_COSTO_ESTADISTICO_1],[I_COSTO_ESTADISTICO_2],[I_COSTO_ESTADISTICO_3],[I_COSTO_ESTADISTICO_4],[I_COSTO_ESTADISTICO_5],[I_COSTO_ESTADISTICO_6],[I_COSTO_ESTADISTICO_7],[I_COSTO_ESTADISTICO_8],[I_COSTO_ESTADISTICO_9]
			,[I_COSTO_ESTADISTICO_10],[I_COSTO_ESTADISTICO_11],[I_COSTO_ESTADISTICO_12],[I_COSTO_ESTADISTICO_13],[I_COSTO_ESTADISTICO_14],[I_COSTO_ESTADISTICO_15],[I_COSTO_ESTADISTICO_16],[I_COSTO_ESTADISTICO_17],[I_COSTO_ESTADISTICO_18],[I_COSTO_ESTADISTICO_19]
			,[I_COSTO_ESTADISTICO_20],[I_COSTO_ESTADISTICO_21],[I_COSTO_ESTADISTICO_22],[I_COSTO_ESTADISTICO_23],[I_COSTO_ESTADISTICO_24],[I_COSTO_ESTADISTICO_25],[I_COSTO_ESTADISTICO_26],[I_COSTO_ESTADISTICO_27],[I_COSTO_ESTADISTICO_28],[I_COSTO_ESTADISTICO_29]
			,[I_COSTO_ESTADISTICO_30],[I_COSTO_ESTADISTICO_31]
			,[I_COSTO_PP_1],[I_COSTO_PP_2],[I_COSTO_PP_3],[I_COSTO_PP_4],[I_COSTO_PP_5],[I_COSTO_PP_6],[I_COSTO_PP_7],[I_COSTO_PP_8],[I_COSTO_PP_9]
			,[I_COSTO_PP_10],[I_COSTO_PP_11],[I_COSTO_PP_12],[I_COSTO_PP_13],[I_COSTO_PP_14],[I_COSTO_PP_15],[I_COSTO_PP_16],[I_COSTO_PP_17],[I_COSTO_PP_18],[I_COSTO_PP_19]
			,[I_COSTO_PP_20],[I_COSTO_PP_21],[I_COSTO_PP_22],[I_COSTO_PP_23],[I_COSTO_PP_24],[I_COSTO_PP_25],[I_COSTO_PP_26],[I_COSTO_PP_27],[I_COSTO_PP_28],[I_COSTO_PP_29]
			,[I_COSTO_PP_30],[I_COSTO_PP_31]
			,[I_COSTO_PARTE_ULTIMO_INGRESO_1],[I_COSTO_PARTE_ULTIMO_INGRESO_2],[I_COSTO_PARTE_ULTIMO_INGRESO_3],[I_COSTO_PARTE_ULTIMO_INGRESO_4],[I_COSTO_PARTE_ULTIMO_INGRESO_5],[I_COSTO_PARTE_ULTIMO_INGRESO_6],[I_COSTO_PARTE_ULTIMO_INGRESO_7],[I_COSTO_PARTE_ULTIMO_INGRESO_8],[I_COSTO_PARTE_ULTIMO_INGRESO_9]
			,[I_COSTO_PARTE_ULTIMO_INGRESO_10],[I_COSTO_PARTE_ULTIMO_INGRESO_11],[I_COSTO_PARTE_ULTIMO_INGRESO_12],[I_COSTO_PARTE_ULTIMO_INGRESO_13],[I_COSTO_PARTE_ULTIMO_INGRESO_14],[I_COSTO_PARTE_ULTIMO_INGRESO_15],[I_COSTO_PARTE_ULTIMO_INGRESO_16],[I_COSTO_PARTE_ULTIMO_INGRESO_17],[I_COSTO_PARTE_ULTIMO_INGRESO_18],[I_COSTO_PARTE_ULTIMO_INGRESO_19]
			,[I_COSTO_PARTE_ULTIMO_INGRESO_20],[I_COSTO_PARTE_ULTIMO_INGRESO_21],[I_COSTO_PARTE_ULTIMO_INGRESO_22],[I_COSTO_PARTE_ULTIMO_INGRESO_23],[I_COSTO_PARTE_ULTIMO_INGRESO_24],[I_COSTO_PARTE_ULTIMO_INGRESO_25],[I_COSTO_PARTE_ULTIMO_INGRESO_26],[I_COSTO_PARTE_ULTIMO_INGRESO_27],[I_COSTO_PARTE_ULTIMO_INGRESO_28],[I_COSTO_PARTE_ULTIMO_INGRESO_29]
			,[I_COSTO_PARTE_ULTIMO_INGRESO_30],[I_COSTO_PARTE_ULTIMO_INGRESO_31]
			,[I_COSTO_COMPRA_ULTIMO_INGRESO_1],[I_COSTO_COMPRA_ULTIMO_INGRESO_2],[I_COSTO_COMPRA_ULTIMO_INGRESO_3],[I_COSTO_COMPRA_ULTIMO_INGRESO_4],[I_COSTO_COMPRA_ULTIMO_INGRESO_5],[I_COSTO_COMPRA_ULTIMO_INGRESO_6],[I_COSTO_COMPRA_ULTIMO_INGRESO_7],[I_COSTO_COMPRA_ULTIMO_INGRESO_8],[I_COSTO_COMPRA_ULTIMO_INGRESO_9]
			,[I_COSTO_COMPRA_ULTIMO_INGRESO_10],[I_COSTO_COMPRA_ULTIMO_INGRESO_11],[I_COSTO_COMPRA_ULTIMO_INGRESO_12],[I_COSTO_COMPRA_ULTIMO_INGRESO_13],[I_COSTO_COMPRA_ULTIMO_INGRESO_14],[I_COSTO_COMPRA_ULTIMO_INGRESO_15],[I_COSTO_COMPRA_ULTIMO_INGRESO_16],[I_COSTO_COMPRA_ULTIMO_INGRESO_17],[I_COSTO_COMPRA_ULTIMO_INGRESO_18],[I_COSTO_COMPRA_ULTIMO_INGRESO_19]
			,[I_COSTO_COMPRA_ULTIMO_INGRESO_20],[I_COSTO_COMPRA_ULTIMO_INGRESO_21],[I_COSTO_COMPRA_ULTIMO_INGRESO_22],[I_COSTO_COMPRA_ULTIMO_INGRESO_23],[I_COSTO_COMPRA_ULTIMO_INGRESO_24],[I_COSTO_COMPRA_ULTIMO_INGRESO_25],[I_COSTO_COMPRA_ULTIMO_INGRESO_26],[I_COSTO_COMPRA_ULTIMO_INGRESO_27],[I_COSTO_COMPRA_ULTIMO_INGRESO_28],[I_COSTO_COMPRA_ULTIMO_INGRESO_29]
			,[I_COSTO_COMPRA_ULTIMO_INGRESO_30],[I_COSTO_COMPRA_ULTIMO_INGRESO_31])) AS UnpivotedTable
)
SELECT 
    C_ANIO,
	C_MES,
	Dia,
    C_ARTICULO,
    C_SUCU_EMPR,  
    Fecha = CAST(C_ANIO AS VARCHAR(4)) + '-' + RIGHT('0' + CAST(C_MES AS VARCHAR(2)), 2) + '-' + RIGHT('0' + CAST(Dia AS VARCHAR(2)), 2),
    PRECIO_VTA,
    COSTO_ESTADISTICO,
    COSTO_PP,
    COSTO_PARTE_ULTIMO_INGRESO,
    COSTO_COMPRA_ULTIMO_INGRESO
INTO T_HISTORIAL_PRECIOS  --- ojo Genera Tabla Fïsica
FROM 
    BaseData
PIVOT (
    MAX(Valor) 
    FOR Tipo_Precio IN (PRECIO_VTA, COSTO_ESTADISTICO, COSTO_PP, COSTO_PARTE_ULTIMO_INGRESO, COSTO_COMPRA_ULTIMO_INGRESO)
) AS PivotedData;

/**************** Toma Origen TT710_ESTADIS_DETALLE

SELECT TOP 1000 CONVERT(varchar(10), [F_DIA],25)as Fecha, * 
--- INTO T_HISTORIAL_VENTAS
FROM [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_DETALLE]
WHERE Q_VENTA <> 0