SELECT [C_ARTICULO]
      ,[C_SUCU_EMPR]
      ,[F_VIGENCIA_DESDE]
      ,[F_VIGENCIA_HASTA]
      ,[C_TIPO_PRECIO]
      ,[I_PRECIO_NUEVO]
      ,[I_PRECIO_RETORNO]
	  ,[I_PRECIO_NUEVO]/[I_PRECIO_RETORNO] as PRECIO_RELATIVO
      ,[C_USUARIO]
      ,[C_TERMINAL]
      ,[F_MODIF]
      ,[M_VIGENTE]
      ,[U_PAGINA]
INTO T_HISTORIAL_OFERTAS
  FROM [DIARCOP001].[DiarcoP].[dbo].[T900_PRECIOS_VIGENCIA]
GO


