/*** PRECIOS DE LA COMPETENCIA   Explorar Entidades ***/
USE [data-sync]
GO

SELECT TOP 1000 *
  FROM [DIARCOP001].[DiarcoP].[dbo].[T090_COMPETENCIA]  --- Cadenas Incluidas en la Comparativa
GO

SELECT TOP 1000 *
  FROM [DIARCOP001].[DiarcoP].[dbo].[T090_COMPETENCIA_ZONAS] --- ZONAS de la Comparativa
GO

SELECT TOP 1000 *
  FROM [DIARCOP001].[DiarcoP].[dbo].[T090_COMPETENCIA_ZONAS_COMPETIDORES] --- COMPETIDORES Incluidos
GO

SELECT TOP 1000 *
  FROM [DIARCOP001].[DiarcoP].[dbo].[T090_COMPETENCIA_ZONAS_SUCURSALES]-- SUCURSALES por ZONA Competencia
GO

SELECT TOP 1000 *
  FROM [DIARCOP001].[DiarcoP].[dbo].[T091_COMPETENCIA_PRECIOS_CABE]   --- CABECERA de la Toma


SELECT TOP 1000 *
  FROM [DIARCOP001].[DiarcoP].[dbo].[T091_COMPETENCIA_PRECIOS_DETA]    --- DETALLE de la Comparativa


/*** DATOS DE LA COMPETENCIA  ***/
SELECT top 1000 A.U_ANIO, A.U_SEMANA,
                      A.C_SUCU_EMPR,A.C_ARTICULO,A.C_PROVEEDOR_PRIMARIO, 
              B.N_ARTICULO, A.I_COSTO_ESTADISTICO, 
                      A.I_PRECIO_VTA, 
              (A.I_PRECIO_VTA - A.I_COSTO_ESTADISTICO) / A.I_COSTO_ESTADISTICO * 100 AS [MG%], 
              A.C_COMPETIDOR, C.N_COMPETIDOR,
                      A.I_PRECIO_COMPETIDOR, 
              (A.I_PRECIO_COMPETIDOR - A.I_COSTO_ESTADISTICO)/ A.I_COSTO_ESTADISTICO * 100 AS [MG2%]

--- INTO T_COMPETENCIA_DETALLE
FROM            [DIARCOP001].[DiarcoP].dbo.T091_COMPETENCIA_PRECIOS_DETA A INNER JOIN
                [DIARCOP001].[DiarcoP].dbo.T050_ARTICULOS B ON A.C_ARTICULO = B.C_ARTICULO INNER JOIN
                [DIARCOP001].[DiarcoP].dbo.T090_COMPETENCIA C ON A.C_COMPETIDOR = C.C_COMPETIDOR
WHERE        (A.U_ANIO = 2025) AND (A.U_SEMANA = 2)

SELECT TOP 1000 * FROM T_COMPETENCIA_DETALLE