SELECT TOP (1000) [C_OC]
      ,T.[U_PREFIJO_OC]
      ,T.[U_SUFIJO_OC]
      ,T.[C_PROVEEDOR]
      ,T.[C_SUCU_COMPRA]
      ,T.[C_SUCU_DESTINO]
      ,T.[C_ARTICULO]
      ,T.[Q_VENTA_DIARIA]
      ,T.[Q_VENTA_MENSUAL]
      ,T.[Q_DIAS_STOCK]
      ,T.[Q_DIAS_ENTREGA_PROVEEDOR]
      ,T.[STOCK_VALORIZADO]
      ,T.[PRECIO_COMPETENCIA]
	  ,M.[Q_VENTA_DIARIA_NORMAL]
	  ,M.[Q_VENTA_30_DIAS] + M.[Q_VENTA_15_DIAS] AS suma
	  ,M.[Q_DIAS_STOCK]
	  ,M.[Q_DIAS_ENTREGA_PROVEEDOR]
  FROM [data-sync].[dbo].[T_OC_DETALLE] T
  LEFT JOIN [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_REPOSICION] M
      ON T.[C_SUCU_COMPRA] = M.[C_SUCU_EMPR]
		AND T.[C_ARTICULO] = M.[C_ARTICULO];  
