SELECT TOP 1000 *
  FROM [DIARCOP001].[DiarcoP].[dbo].[T061_STOCK_DIARIO]


SELECT TOP 1000 *
	FROM [DIARCOP001].[DiarcoP].[dbo].[T051_ARTICULOS_SUCURSAL_ESTADIST]
SELECT TOP 1000 *
	FROM [DIARCOP001].[DiarcoP].[dbo].[T055_ARTICULOS_PARAM_STOCK]
SELECT TOP 1000 *
	FROM [DIARCOP001].[DiarcoP].[dbo].[T055_ARTICULOS_SUCURSAL_PROVEEDOR_DIAS_ENTREGA]

SELECT TOP 1000 *
	FROM [DIARCOP001].[DiarcoP]-[dbo].[T080_OC_PRECARGA_KIKKER]
SELECT TOP 1000 *
	FROM [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS]
SELECT TOP 1000 *
	FROM [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_REPOSICION]
	[dbo].[T020_PROVEEDOR]


/*** PRUEBAS RECOLECCIÓN DATOS PARA PEDIDOS ***/

SELECT TOP 1000 
	   R.[C_SUCU_EMPR]
      ,R.[C_ARTICULO]
      ,R.[Q_VENTA_30_DIAS]
      ,R.[Q_VENTA_15_DIAS]
      ,R.[Q_VENTA_DOMINGO]
      ,R.[Q_VENTA_ESPECIAL_30_DIAS]
      ,R.[Q_VENTA_ESPECIAL_15_DIAS]
      ,R.[Q_DIAS_CON_STOCK]
      ,R.[Q_REPONER]
      ,R.[Q_REPONER_INCLUIDO_SOBRE_STOCK]
      ,R.[M_SEMAFORO_INDIVIDUAL]
      ,R.[M_SEMAFORO_GLOBAL]
      ,R.[Q_VENTA_DIARIA_NORMAL]
      ,R.[Q_DIAS_STOCK]
      ,R.[Q_DIAS_SOBRE_STOCK]
      ,R.[Q_DIAS_ENTREGA_PROVEEDOR]
	  ,'ARTICULO' as TABLA1
	  ,A.[C_ARTICULO]
      ,A.[C_FAMILIA]
      ,A.[C_RUBRO]
      ,A.[C_PROVEEDOR_PRIMARIO]
      ,A.[N_ARTICULO]
      ,A.[N_ARTICULO_FACT]
      ,A.[C_MARCA]
      ,A.[C_ENVASE]
      ,A.[Q_PESO_UNIT_ART]
      ,A.[Q_FACTOR_VENTA_ESP]
      ,A.[M_BAJA]
      ,A.[F_BAJA]
      ,A.[M_OCASION]
      ,A.[M_BEBIDA_ALCOHOLICA]
      ,A.[C_UNIDAD_MEDIDA]
      ,A.[Q_UNIDAD_MEDIDA]
      ,A.[C_UNICO_PRODUCTO_TRANSP_1]
      ,A.[C_UNID_MEDIDA_TRANSP_1]
      ,A.[C_COMPRADOR]
      ,A.[D_AVISO_PROMOCION]
      ,A.[M_SENSIBLE_VENTA]
      ,A.[OK_COMPRA]
      ,A.[M_TOP]
      ,A.[M_VARIEDAD_EXTRA]
      ,A.[M_SIN_VENTA]
      ,A.[M_RESTO_TOP]
      ,A.[C_CLASIFICACION_COMPRA]
      ,A.[C_ARTICULO_ALTERNATIVO]
      ,A.[C_PRESENTACION]
      ,A.[M_PRECIO_CUIDADO]
      ,A.[M_BULTO_TRANSPARENTE]
      ,A.[M_CONTROLO_SIEMPRE]
      ,A.[M_PALLETS]
      ,A.[M_ARTICULO_PADRE_PRECIO]
      ,A.[M_ARTICULO_CON_SUSTITUTOS]
      ,A.[M_LIQ_PRODUCTO]
      ,A.[M_KOSHER]
	  ,'PROVEEDOR' as TABLA2
	  ,P.[C_PROVEEDOR]
      ,P.[C_TIPO_PROVEEDOR]
      ,P.[C_TIPO_PROVEEDOR_DIARCO]  
      ,P.[N_PROVEEDOR]
      ,P.[C_PLAZO_ENTREGA1]
      ,P.[M_ATEN_CLIE_LUN]
      ,P.[M_ATEN_CLIE_MAR]
      ,P.[M_ATEN_CLIE_MIE]
      ,P.[M_ATEN_CLIE_JUE]
      ,P.[M_ATEN_CLIE_VIE]
      ,P.[M_ATEN_CLIE_SAB]
      ,P.[M_ATEN_CLIE_DOM] 
      ,P.[M_COMPRA_PALETIZADO] 
      ,P.[U_DIAS_TOPE_PARA_AGENDA]
      ,P.[U_DIAS_TOPE_PARA_INGRESO_AGENDA]
      ,P.[M_ATEN_PROV_LUN]
      ,P.[M_ATEN_PROV_MAR]
      ,P.[M_ATEN_PROV_MIE]
      ,P.[M_ATEN_PROV_JUE]
      ,P.[M_ATEN_PROV_VIE]
      ,P.[M_ATEN_PROV_SAB]
      ,P.[M_ATEN_PROV_DOM]
      ,P.[C_PERIODO_ATENCION_AGENDA]
      ,P.[U_DIAS_PAGO]
      ,P.[C_CLIENTE]
	  ,P.[C_NIVEL_PROVEEDOR]


	FROM [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_REPOSICION] R
	LEFT JOIN [DIARCOP001].[DiarcoP].[dbo].[T050_ARTICULOS] A
		ON R.[C_ARTICULO] = A.[C_ARTICULO]
	LEFT JOIN [DIARCOP001].[DiarcoP].[dbo].[T020_PROVEEDOR] P
		ON A.[C_PROVEEDOR_PRIMARIO] = P.[C_PROVEEDOR]

	WHERE P.[C_PROVEEDOR] = 6370