USE [data-sync]
GO

/****** Object:  StoredProcedure [repl].[usp_replicar_T080_OC_CABE]    Script Date: 09/06/2025 14:25:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE OR ALTER       PROCEDURE [repl].[usp_replicar_T080_OC_CABE]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T080_OC_CABE_STG;

        INSERT INTO repl.T080_OC_CABE_STG (
            C_OC, U_PREFIJO_OC, U_SUFIJO_OC, U_PREFIJO_LOTE, U_LOTE, M_OC_MADRE, M_OC_PARA_TRANSFERENCIA, M_OC_PAGOANT, U_DIAS_LIMITE_ENTREGA, C_PROVEEDOR, C_SUCU_COMPRA, C_SUCU_DESTINO, C_SUCU_DESTINO_ALT, 
			C_SITUAC, F_SITUAC, F_ALTA_SIST, F_EMISION, F_ENTREGA, I_NETO_OC, I_IVA_OC, I_IMP_INTERNO_OC, I_TOTAL_OC, C_COMPRADOR, C_USUARIO_OPERADOR, C_TERMINAL_OPERADOR, C_USUARIO_CUMPLIO, C_TIPO, 
			C_PLAZO_ENTREGA1, C_PLAZO_ENTREGA2, C_PLAZO_ENTREGA3, C_PLAZO_ENTREGA4, C_PLAZO_ENTREGA5, C_PLAZO_ENTREGA6, D_COND_PAGO, D_OBSERVACION, F_COMP_ING_MERC, C_COMP_ING_MERC, U_PREFIJO_COMP_ING_MERC, 
			U_SUFIJO_COMP_ING_MERC, D_OBSERVACION_ING_MERC, C_TIPO_ENTREGA_MERCADERIA, C_USUARIO_MODIFICO, C_TERMINAL_MODIFICO, F_MODIFICO, M_OC_ELECTRONICA, C_SITUAC_OC_ELECTRONICA, F_SITUAC_OC_ELECTRONICA, 
			M_ENVIADO, M_ESP, C_TIPO_PROVEEDOR_EDI, FECHA_LIMITE, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_OC,U_PREFIJO_OC,U_SUFIJO_OC,U_PREFIJO_LOTE,U_LOTE,M_OC_MADRE,M_OC_PARA_TRANSFERENCIA,M_OC_PAGOANT,U_DIAS_LIMITE_ENTREGA,C_PROVEEDOR,C_SUCU_COMPRA,C_SUCU_DESTINO,C_SUCU_DESTINO_ALT,
			C_SITUAC,F_SITUAC,F_ALTA_SIST,F_EMISION,F_ENTREGA,I_NETO_OC,I_IVA_OC,I_IMP_INTERNO_OC,I_TOTAL_OC,C_COMPRADOR,C_USUARIO_OPERADOR,C_TERMINAL_OPERADOR,C_USUARIO_CUMPLIO,C_TIPO,
			C_PLAZO_ENTREGA1,C_PLAZO_ENTREGA2,C_PLAZO_ENTREGA3,C_PLAZO_ENTREGA4,C_PLAZO_ENTREGA5,C_PLAZO_ENTREGA6,D_COND_PAGO,D_OBSERVACION,F_COMP_ING_MERC,C_COMP_ING_MERC,U_PREFIJO_COMP_ING_MERC,
			U_SUFIJO_COMP_ING_MERC,D_OBSERVACION_ING_MERC,C_TIPO_ENTREGA_MERCADERIA,C_USUARIO_MODIFICO,C_TERMINAL_MODIFICO,F_MODIFICO,M_OC_ELECTRONICA,C_SITUAC_OC_ELECTRONICA,F_SITUAC_OC_ELECTRONICA,
			M_ENVIADO,M_ESP,C_TIPO_PROVEEDOR_EDI,
			ISNULL(DATEADD(DAY, [U_DIAS_LIMITE_ENTREGA], [F_ENTREGA]), GETDATE()) AS FECHA_LIMITE,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
		
        FROM [DIARCOP001].[DiarcoP].[dbo].[T080_OC_CABE]
        WHERE F_EMISION >= '2025-04-01';

        
        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();

		IF XACT_STATE() <> 0
            ROLLBACK;
		
        INSERT INTO repl.LOGS_T080_OC_CABE_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

	BEGIN TRY
		INSERT INTO repl.LOGS_T080_OC_CABE_SYNC (
			fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
		) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
	END TRY
	BEGIN CATCH
    END CATCH
END;
GO


