SELECT TOP 100 [F_VENTA]
      ,[C_ARTICULO]
      ,[C_FAMILIA]
      ,[C_SUCU_EMPR]
      ,[I_PRECIO_VENTA]
      ,[I_PRECIO_COSTO]
      ,[I_VENDIDO]
      ,[Q_UNIDADES_VENDIDAS]
      ,[I_PRECIO_COSTO_PP]
      ,[I_PARTE_ULTIMO_INGRESO]
      ,[I_COMPRA_ULTIMO_INGRESO]
      ,[I_IMP_INTERNOS]
  FROM [DCO-DBCORE-P02].[DiarcoEst].[dbo].[T702_EST_VTAS_POR_ARTICULO]
GO


