/*** CREAR TABLA ***/
USE [data-sync]
GO

/****** Object:  Table [repl].[T710_ESTADIS_STOCK]    Script Date: 07/05/2025 10:23:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [repl].[T710_ESTADIS_STOCK](
	[C_ANIO] [decimal](4, 0) NOT NULL,[C_MES] [decimal](2, 0) NOT NULL,[C_SUCU_EMPR] [decimal](3, 0) NOT NULL,[C_ARTICULO] [decimal](6, 0) NOT NULL,[Q_DIA1] [decimal](11, 3) NOT NULL,
	[Q_DIA2] [decimal](11, 3) NOT NULL,[Q_DIA3] [decimal](11, 3) NOT NULL,[Q_DIA4] [decimal](11, 3) NOT NULL,[Q_DIA5] [decimal](11, 3) NOT NULL,[Q_DIA6] [decimal](11, 3) NOT NULL,
	[Q_DIA7] [decimal](11, 3) NOT NULL,[Q_DIA8] [decimal](11, 3) NOT NULL,[Q_DIA9] [decimal](11, 3) NOT NULL,[Q_DIA10] [decimal](11, 3) NOT NULL,[Q_DIA11] [decimal](11, 3) NOT NULL,
	[Q_DIA12] [decimal](11, 3) NOT NULL,[Q_DIA13] [decimal](11, 3) NOT NULL,[Q_DIA14] [decimal](11, 3) NOT NULL,[Q_DIA15] [decimal](11, 3) NOT NULL,[Q_DIA16] [decimal](11, 3) NOT NULL,
	[Q_DIA17] [decimal](11, 3) NOT NULL,[Q_DIA18] [decimal](11, 3) NOT NULL,[Q_DIA19] [decimal](11, 3) NOT NULL,[Q_DIA20] [decimal](11, 3) NOT NULL,[Q_DIA21] [decimal](11, 3) NOT NULL,
	[Q_DIA22] [decimal](11, 3) NOT NULL,[Q_DIA23] [decimal](11, 3) NOT NULL,[Q_DIA24] [decimal](11, 3) NOT NULL,[Q_DIA25] [decimal](11, 3) NOT NULL,[Q_DIA26] [decimal](11, 3) NOT NULL,
	[Q_DIA27] [decimal](11, 3) NOT NULL,[Q_DIA28] [decimal](11, 3) NOT NULL,[Q_DIA29] [decimal](11, 3) NOT NULL,[Q_DIA30] [decimal](11, 3) NOT NULL,[Q_DIA31] [decimal](11, 3) NOT NULL,
	Fecha_Proceso DATETIME2, procesado_ok BIT
CONSTRAINT [PK_T710_ESTADIS_STOCK] PRIMARY KEY CLUSTERED 
(
	[C_ANIO] ASC,
	[C_MES] ASC,
	[C_SUCU_EMPR] ASC,
	[C_ARTICULO] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA1]  DEFAULT (0) FOR [Q_DIA1]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA2]  DEFAULT (0) FOR [Q_DIA2]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA3]  DEFAULT (0) FOR [Q_DIA3]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA4]  DEFAULT (0) FOR [Q_DIA4]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA5]  DEFAULT (0) FOR [Q_DIA5]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA6]  DEFAULT (0) FOR [Q_DIA6]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA7]  DEFAULT (0) FOR [Q_DIA7]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA8]  DEFAULT (0) FOR [Q_DIA8]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA9]  DEFAULT (0) FOR [Q_DIA9]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA10]  DEFAULT (0) FOR [Q_DIA10]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA11]  DEFAULT (0) FOR [Q_DIA11]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA12]  DEFAULT (0) FOR [Q_DIA12]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA13]  DEFAULT (0) FOR [Q_DIA13]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA14]  DEFAULT (0) FOR [Q_DIA14]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA15]  DEFAULT (0) FOR [Q_DIA15]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA16]  DEFAULT (0) FOR [Q_DIA16]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA17]  DEFAULT (0) FOR [Q_DIA17]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA18]  DEFAULT (0) FOR [Q_DIA18]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA19]  DEFAULT (0) FOR [Q_DIA19]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA20]  DEFAULT (0) FOR [Q_DIA20]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA21]  DEFAULT (0) FOR [Q_DIA21]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA22]  DEFAULT (0) FOR [Q_DIA22]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA23]  DEFAULT (0) FOR [Q_DIA23]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA24]  DEFAULT (0) FOR [Q_DIA24]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA25]  DEFAULT (0) FOR [Q_DIA25]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA26]  DEFAULT (0) FOR [Q_DIA26]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA27]  DEFAULT (0) FOR [Q_DIA27]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA28]  DEFAULT (0) FOR [Q_DIA28]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA29]  DEFAULT (0) FOR [Q_DIA29]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA30]  DEFAULT (0) FOR [Q_DIA30]
GO

ALTER TABLE [repl].[T710_ESTADIS_STOCK] ADD  CONSTRAINT [DF_T710_ESTADIS_STOCK_Q_DIA31]  DEFAULT (0) FOR [Q_DIA31]
GO

/* INSERTAR DATOS */

USE [data-sync]
GO

INSERT INTO [repl].[T710_ESTADIS_STOCK]
    ([C_ANIO],[C_MES],[C_SUCU_EMPR],[C_ARTICULO],[Q_DIA1],[Q_DIA2],[Q_DIA3],[Q_DIA4],[Q_DIA5],[Q_DIA6],[Q_DIA7],[Q_DIA8],[Q_DIA9]
	,[Q_DIA10],[Q_DIA11],[Q_DIA12],[Q_DIA13],[Q_DIA14],[Q_DIA15],[Q_DIA16],[Q_DIA17],[Q_DIA18],[Q_DIA19],[Q_DIA20]
	,[Q_DIA21],[Q_DIA22],[Q_DIA23],[Q_DIA24],[Q_DIA25],[Q_DIA26],[Q_DIA27],[Q_DIA28],[Q_DIA29],[Q_DIA30],[Q_DIA31]
	,[Fecha_Proceso],[procesado_ok])

	SELECT [C_ANIO],[C_MES],[C_SUCU_EMPR],[C_ARTICULO],[Q_DIA1],[Q_DIA2],[Q_DIA3],[Q_DIA4],[Q_DIA5],[Q_DIA6],[Q_DIA7],[Q_DIA8],[Q_DIA9]
	,[Q_DIA10],[Q_DIA11],[Q_DIA12],[Q_DIA13],[Q_DIA14],[Q_DIA15],[Q_DIA16],[Q_DIA17],[Q_DIA18],[Q_DIA19],[Q_DIA20]
	,[Q_DIA21],[Q_DIA22],[Q_DIA23],[Q_DIA24],[Q_DIA25],[Q_DIA26],[Q_DIA27],[Q_DIA28],[Q_DIA29],[Q_DIA30],[Q_DIA31]
	,GETDATE() AS Fecha_Proceso
	,CAST(0 AS BIT) AS Procesado

	 FROM [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_STOCK]
	 WHERE C_ANIO > 2023
GO

/* VALIDAR DATOS PORQUE PARECE RARO */

SELECT TOP 100 C_ANIO, C_MES, C_SUCU_EMPR, C_ARTICULO, 
        Q_DIA1, Q_DIA2, Q_DIA3, Q_DIA4, Q_DIA5, Q_DIA6, Q_DIA7, Q_DIA8, Q_DIA9, 
        Q_DIA10, Q_DIA11, Q_DIA12, Q_DIA13, Q_DIA14, Q_DIA15, Q_DIA16, Q_DIA17, Q_DIA18, Q_DIA19, 
        Q_DIA20, Q_DIA21, Q_DIA22, Q_DIA23, Q_DIA24, Q_DIA25, Q_DIA26, Q_DIA27, Q_DIA28, Q_DIA29, 
        Q_DIA30, Q_DIA31
    FROM [data-sync].[repl].[T710_ESTADIS_STOCK]
    WHERE C_ANIO = 2025 AND C_MES >= MONTH(DATEADD(MONTH, -1, GETDATE()))


-- Transofrmarlo Directamente en ORIGEN - 2 ultimos meses calendario

SELECT 
    C_ANIO AS Anio,
    C_MES AS Mes,
    CAST(REPLACE(Dia, 'Q_DIA', '') AS INT) AS Dia, -- Extraemos el número de día del nombre de la columna
    C_SUCU_EMPR AS Sucursal,
    C_ARTICULO AS Articulo,
    Cantidad,
	TRY_CAST(CONCAT(C_ANIO, '-', RIGHT('0' + CAST(C_MES AS VARCHAR), 2), '-', RIGHT('0' + CAST(REPLACE(Dia, 'Q_DIA', '') AS VARCHAR), 2)) AS DATE) AS Fecha_Stock,
	--CAST(CONCAT(C_ANIO, '-', RIGHT('0' + CAST(C_MES AS VARCHAR), 2), '-', RIGHT('0' + CAST(REPLACE(Dia, 'Q_DIA', '') AS VARCHAR), 2)) AS DATE) AS Fecha,
    GETDATE() AS Fecha_Procesos,
    CAST(0 AS BIT) AS Procesado
INTO [repl].[Historico_Stock_Sucursal]
FROM (
    SELECT C_ANIO, C_MES, C_SUCU_EMPR, C_ARTICULO, 
        Q_DIA1, Q_DIA2, Q_DIA3, Q_DIA4, Q_DIA5, Q_DIA6, Q_DIA7, Q_DIA8, Q_DIA9, 
        Q_DIA10, Q_DIA11, Q_DIA12, Q_DIA13, Q_DIA14, Q_DIA15, Q_DIA16, Q_DIA17, Q_DIA18, Q_DIA19, 
        Q_DIA20, Q_DIA21, Q_DIA22, Q_DIA23, Q_DIA24, Q_DIA25, Q_DIA26, Q_DIA27, Q_DIA28, Q_DIA29, 
        Q_DIA30, Q_DIA31
    FROM [data-sync].[repl].[T710_ESTADIS_STOCK]
    WHERE C_ANIO = 2025 AND C_MES >= MONTH(DATEADD(MONTH, -1, GETDATE()))

) AS DataOrigen
UNPIVOT (
    Cantidad FOR Dia IN (
        Q_DIA1, Q_DIA2, Q_DIA3, Q_DIA4, Q_DIA5, Q_DIA6, Q_DIA7, Q_DIA8, Q_DIA9, 
        Q_DIA10, Q_DIA11, Q_DIA12, Q_DIA13, Q_DIA14, Q_DIA15, Q_DIA16, Q_DIA17, Q_DIA18, Q_DIA19, 
        Q_DIA20, Q_DIA21, Q_DIA22, Q_DIA23, Q_DIA24, Q_DIA25, Q_DIA26, Q_DIA27, Q_DIA28, Q_DIA29, 
        Q_DIA30, Q_DIA31
    )
) AS DataTransformada;

/** Como la tabla es fija, y aparece columna 31 para Febrero hay que borrar los que dieron Fecha Sotck = NULL */

DELETE  FROM [repl].[Historico_Stock_Sucursal] WHERE Fecha_Stock IS NULL


/***** RUTINA DE ACTUALIZACIÓN ****/
SELECT MAX([Fecha_Procesos]) FROM [repl].[Historico_Stock_Sucursal] 



INSERT INTO [repl].[Historico_Stock_Sucursal]
           ([Anio],[Mes],[Dia],[Sucursal],[Articulo],[Cantidad],[Fecha_Stock],[Fecha_Procesos],[Procesado])
		
	SELECT TOP 100
			C_ANIO AS Anio,
			C_MES AS Mes,
			CAST(REPLACE(Dia, 'Q_DIA', '') AS INT) AS Dia, -- Extraemos el número de día del nombre de la columna
			C_SUCU_EMPR AS Sucursal,
			C_ARTICULO AS Articulo,
			Cantidad,
			TRY_CAST(CONCAT(C_ANIO, '-', RIGHT('0' + CAST(C_MES AS VARCHAR), 2), '-', RIGHT('0' + CAST(REPLACE(Dia, 'Q_DIA', '') AS VARCHAR), 2)) AS DATE) AS Fecha_Stock,
			--CAST(CONCAT(C_ANIO, '-', RIGHT('0' + CAST(C_MES AS VARCHAR), 2), '-', RIGHT('0' + CAST(REPLACE(Dia, 'Q_DIA', '') AS VARCHAR), 2)) AS DATE) AS Fecha,
			GETDATE() AS Fecha_Procesos,
			CAST(0 AS BIT) AS Procesado

		FROM (
			SELECT C_ANIO, C_MES, C_SUCU_EMPR, C_ARTICULO, 
				Q_DIA1, Q_DIA2, Q_DIA3, Q_DIA4, Q_DIA5, Q_DIA6, Q_DIA7, Q_DIA8, Q_DIA9, 
				Q_DIA10, Q_DIA11, Q_DIA12, Q_DIA13, Q_DIA14, Q_DIA15, Q_DIA16, Q_DIA17, Q_DIA18, Q_DIA19, 
				Q_DIA20, Q_DIA21, Q_DIA22, Q_DIA23, Q_DIA24, Q_DIA25, Q_DIA26, Q_DIA27, Q_DIA28, Q_DIA29, 
				Q_DIA30, Q_DIA31
			FROM [data-sync].[repl].[T710_ESTADIS_STOCK]
			WHERE C_ANIO = 2025 AND C_MES >= MONTH(DATEADD(MONTH, -1, GETDATE()))

		) AS DataOrigen
		UNPIVOT (
			Cantidad FOR Dia IN (
				Q_DIA1, Q_DIA2, Q_DIA3, Q_DIA4, Q_DIA5, Q_DIA6, Q_DIA7, Q_DIA8, Q_DIA9, 
				Q_DIA10, Q_DIA11, Q_DIA12, Q_DIA13, Q_DIA14, Q_DIA15, Q_DIA16, Q_DIA17, Q_DIA18, Q_DIA19, 
				Q_DIA20, Q_DIA21, Q_DIA22, Q_DIA23, Q_DIA24, Q_DIA25, Q_DIA26, Q_DIA27, Q_DIA28, Q_DIA29, 
				Q_DIA30, Q_DIA31
			)
		) AS DataTransformada
		
	WHERE Fecha_Procesos > '2025-05-06' ;

/** Como la tabla es fija, y aparece columna 31 para Febrero hay que borrar los que dieron Fecha Sotck = NULL */
GO