USE [data-sync]
GO

TRUNCATE TABLE T_100_SUCURSALES
GO

INSERT INTO [dbo].[T_100_SUCURSALES]
           ([C_SUCU_EMPR]
           ,[N_SUCURSAL]
           ,[N_SUCURSAL_ABREV]
           ,[N_SUCURSAL_ABREV2]
           ,[N_SUCURSAL_ABREV3]
           ,[N_CALLE]
           ,[N_LOCALIDAD]
           ,[C_POSTAL_INM]
           ,[C_PROVINCIA_SUCU]
           ,[C_ZONA]
           ,[C_ZONA_REGIONAL]
           ,[CLUSTER_LOG]
           ,[C_FORMATO]
           ,[FORMATO]
           ,[M_BAJA]
           ,[ETIQUETA])

SELECT   LTRIM(RTRIM(REPLACE([C_SUCU_EMPR], CHAR(9), ''))) AS C_SUCU_EMPR,
    LTRIM(RTRIM(REPLACE([N_SUCURSAL], CHAR(9), ''))) AS N_SUCURSAL,
    LTRIM(RTRIM(REPLACE([N_SUCURSAL_ABREV], CHAR(9), ''))) AS N_SUCURSAL_ABREV,
    LTRIM(RTRIM(REPLACE([N_SUCURSAL_ABREV2], CHAR(9), ''))) AS N_SUCURSAL_ABREV2,
    LTRIM(RTRIM(REPLACE([N_SUCURSAL_ABREV3], CHAR(9), ''))) AS N_SUCURSAL_ABREV3,
    LTRIM(RTRIM(REPLACE([N_CALLE], CHAR(9), ''))) AS N_CALLE,
    LTRIM(RTRIM(REPLACE([N_LOCALIDAD], CHAR(9), ''))) AS N_LOCALIDAD,
    LTRIM(RTRIM(REPLACE([C_POSTAL_INM], CHAR(9), ''))) AS C_POSTAL_INM,
    LTRIM(RTRIM(REPLACE([C_PROVINCIA_SUCU], CHAR(9), ''))) AS C_PROVINCIA_SUCU,
    LTRIM(RTRIM(REPLACE([C_ZONA], CHAR(9), ''))) AS C_ZONA,
    LTRIM(RTRIM(REPLACE([C_ZONA_REGIONAL], CHAR(9), ''))) AS C_ZONA_REGIONAL
	 ,'CENTRO-M' as CLUSTER_LOG
	 , 1 AS C_FORMATO
	 ,'MAYORISTA' AS FORMATO
	 ,LTRIM(RTRIM(REPLACE([M_BAJA], CHAR(9), ''))) AS M_BAJA
	 ,CONCAT( 'M-', FORMAT(C_SUCU_EMPR, '000'), '-', N_SUCURSAL_ABREV2)AS ETIQUETA

  FROM [DIARCOP001].[DiarcoP].[dbo].[T100_EMPRESA_SUC]
GO

--- SELECT * FROM [DIARCOP001].[DiarcoP].[dbo].[T100_EMPRESA_SUC]
--- ACTUALIZAR CLUSTER LOGÍSTICO
UPDATE T
SET 
    T.CLUSTER_LOG = C.CLUSTER_LOG,
    T.FORMATO = C.FORMATO

FROM [data-sync].[dbo].[T_100_SUCURSALES] T
INNER JOIN [data-sync].[dbo].[CLUSTER_LOGISTICO] C
    ON C.C_SUCU_EMPR = T.C_SUCU_EMPR;



