SELECT --- TOP (1000) 
		A.[C_PROVEEDOR_PRIMARIO] ID
		,P.[N_PROVEEDOR] PROVEEDOR
      --,[C_FAMILIA]
      --,[C_RUBRO]
      --,[C_SUBRUBRO_1]
      --,[C_SUBRUBRO_2]      
       ,[N_ARTICULO]
      --,[M_VENDE_POR_PESO]
      --,[M_A_DAR_DE_BAJA]
      --,[M_BAJA]
      --,[F_BAJA]
  
      ,A.[C_COMPRADOR] CMP
	  ,C.N_COMPRADOR NOMBRE
	 -- , COUNT([C_ARTICULO] ) as ARTICULOS

  FROM [data-sync].[dbo].[T050_ARTICULOS] A
  LEFT JOIN [dbo].[T020_PROVEEDOR] P
  ON P.C_PROVEEDOR = A.C_PROVEEDOR_PRIMARIO
  LEFT JOIN [dbo].[M_9_COMPRADORES] C
  ON A.C_COMPRADOR = C.COD_COMPRADOR

  WHERE C_COMPRADOR = 122
 -- GROUP BY A.C_PROVEEDOR_PRIMARIO, P.[N_PROVEEDOR], A.C_COMPRADOR, C.N_COMPRADOR 
  ORDer BY  A.C_PROVEEDOR_PRIMARIO, A.C_COMPRADOR
