USE [data-sync]
GO

/****** Object:  StoredProcedure [repl].[usp_replicar_T080_OC_CABE]    Script Date: 18/05/2025 12:19:24 ******/
DROP PROCEDURE [repl].[usp_replicar_T080_OC_CABE]
GO

/****** Object:  StoredProcedure [repl].[usp_replicar_T080_OC_CABE]    Script Date: 18/05/2025 12:19:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE   PROCEDURE [repl].[usp_replicar_T080_OC_CABE]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @inicio DATETIME = GETDATE();
    DECLARE @mensaje NVARCHAR(4000);
    DECLARE @total INT = 0;

    BEGIN TRY
        TRUNCATE TABLE repl.T080_OC_CABE_STG;

        INSERT INTO repl.T080_OC_CABE_STG (
            C_OC, U_PREFIJO_OC, U_SUFIJO_OC, U_PREFIJO_LOTE, U_LOTE, M_OC_MADRE, M_OC_PARA_TRANSFERENCIA, M_OC_PAGOANT, U_DIAS_LIMITE_ENTREGA, C_PROVEEDOR, C_SUCU_COMPRA, C_SUCU_DESTINO, C_SUCU_DESTINO_ALT, 
			C_SITUAC, F_SITUAC, F_ALTA_SIST, F_EMISION, F_ENTREGA, I_NETO_OC, I_IVA_OC, I_IMP_INTERNO_OC, I_TOTAL_OC, C_COMPRADOR, C_USUARIO_OPERADOR, C_TERMINAL_OPERADOR, C_USUARIO_CUMPLIO, C_TIPO, 
			C_PLAZO_ENTREGA1, C_PLAZO_ENTREGA2, C_PLAZO_ENTREGA3, C_PLAZO_ENTREGA4, C_PLAZO_ENTREGA5, C_PLAZO_ENTREGA6, D_COND_PAGO, D_OBSERVACION, F_COMP_ING_MERC, C_COMP_ING_MERC, U_PREFIJO_COMP_ING_MERC, 
			U_SUFIJO_COMP_ING_MERC, D_OBSERVACION_ING_MERC, C_TIPO_ENTREGA_MERCADERIA, C_USUARIO_MODIFICO, C_TERMINAL_MODIFICO, F_MODIFICO, M_OC_ELECTRONICA, C_SITUAC_OC_ELECTRONICA, F_SITUAC_OC_ELECTRONICA, 
			M_ENVIADO, M_ESP, C_TIPO_PROVEEDOR_EDI, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION
        )
        SELECT
            C_OC,U_PREFIJO_OC,U_SUFIJO_OC,U_PREFIJO_LOTE,U_LOTE,M_OC_MADRE,M_OC_PARA_TRANSFERENCIA,M_OC_PAGOANT,U_DIAS_LIMITE_ENTREGA,C_PROVEEDOR,C_SUCU_COMPRA,C_SUCU_DESTINO,C_SUCU_DESTINO_ALT,
			C_SITUAC,F_SITUAC,F_ALTA_SIST,F_EMISION,F_ENTREGA,I_NETO_OC,I_IVA_OC,I_IMP_INTERNO_OC,I_TOTAL_OC,C_COMPRADOR,C_USUARIO_OPERADOR,C_TERMINAL_OPERADOR,C_USUARIO_CUMPLIO,C_TIPO,
			C_PLAZO_ENTREGA1,C_PLAZO_ENTREGA2,C_PLAZO_ENTREGA3,C_PLAZO_ENTREGA4,C_PLAZO_ENTREGA5,C_PLAZO_ENTREGA6,D_COND_PAGO,D_OBSERVACION,F_COMP_ING_MERC,C_COMP_ING_MERC,U_PREFIJO_COMP_ING_MERC,
			U_SUFIJO_COMP_ING_MERC,D_OBSERVACION_ING_MERC,C_TIPO_ENTREGA_MERCADERIA,C_USUARIO_MODIFICO,C_TERMINAL_MODIFICO,F_MODIFICO,M_OC_ELECTRONICA,C_SITUAC_OC_ELECTRONICA,F_SITUAC_OC_ELECTRONICA,
			M_ENVIADO,M_ESP,C_TIPO_PROVEEDOR_EDI,
            'DIARCOP001' AS FUENTE_ORIGEN,
            GETDATE() AS FECHA_EXTRACCION,
            CONVERT(VARBINARY(10), NULL) AS CDC_LSN,
            0 AS ESTADO_SINCRONIZACION
        FROM [DIARCOP001].[DiarcoP].[dbo].[T080_OC_CABE]
        WHERE F_EMISION > '2025-02-01';

        MERGE repl.T080_OC_CABE AS TARGET
        USING repl.T080_OC_CABE_STG AS SOURCE
        ON TARGET.C_OC = SOURCE.C_OC

        WHEN MATCHED THEN
            UPDATE SET
                TARGET.U_PREFIJO_OC = SOURCE.U_PREFIJO_OC,
                TARGET.U_SUFIJO_OC = SOURCE.U_SUFIJO_OC,
                TARGET.U_PREFIJO_LOTE = SOURCE.U_PREFIJO_LOTE,
                TARGET.U_LOTE = SOURCE.U_LOTE,
                TARGET.M_OC_MADRE = SOURCE.M_OC_MADRE,
                TARGET.M_OC_PARA_TRANSFERENCIA = SOURCE.M_OC_PARA_TRANSFERENCIA,
                TARGET.M_OC_PAGOANT = SOURCE.M_OC_PAGOANT,
                TARGET.U_DIAS_LIMITE_ENTREGA = SOURCE.U_DIAS_LIMITE_ENTREGA,
                TARGET.C_PROVEEDOR = SOURCE.C_PROVEEDOR,
                TARGET.C_SUCU_COMPRA = SOURCE.C_SUCU_COMPRA,
                TARGET.C_SUCU_DESTINO = SOURCE.C_SUCU_DESTINO,
                TARGET.C_SUCU_DESTINO_ALT = SOURCE.C_SUCU_DESTINO_ALT,
                TARGET.C_SITUAC = SOURCE.C_SITUAC,
                TARGET.F_SITUAC = SOURCE.F_SITUAC,
                TARGET.F_ALTA_SIST = SOURCE.F_ALTA_SIST,
                TARGET.F_EMISION = SOURCE.F_EMISION,
                TARGET.F_ENTREGA = SOURCE.F_ENTREGA,
                TARGET.I_NETO_OC = SOURCE.I_NETO_OC,
                TARGET.I_IVA_OC = SOURCE.I_IVA_OC,
                TARGET.I_IMP_INTERNO_OC = SOURCE.I_IMP_INTERNO_OC,
                TARGET.I_TOTAL_OC = SOURCE.I_TOTAL_OC,
                TARGET.C_COMPRADOR = SOURCE.C_COMPRADOR,
                TARGET.C_USUARIO_OPERADOR = SOURCE.C_USUARIO_OPERADOR,
                TARGET.C_TERMINAL_OPERADOR = SOURCE.C_TERMINAL_OPERADOR,
                TARGET.C_USUARIO_CUMPLIO = SOURCE.C_USUARIO_CUMPLIO,
                TARGET.C_TIPO = SOURCE.C_TIPO,
                TARGET.C_PLAZO_ENTREGA1 = SOURCE.C_PLAZO_ENTREGA1,
                TARGET.C_PLAZO_ENTREGA2 = SOURCE.C_PLAZO_ENTREGA2,
                TARGET.C_PLAZO_ENTREGA3 = SOURCE.C_PLAZO_ENTREGA3,
                TARGET.C_PLAZO_ENTREGA4 = SOURCE.C_PLAZO_ENTREGA4,
                TARGET.C_PLAZO_ENTREGA5 = SOURCE.C_PLAZO_ENTREGA5,
                TARGET.C_PLAZO_ENTREGA6 = SOURCE.C_PLAZO_ENTREGA6,
                TARGET.D_COND_PAGO = SOURCE.D_COND_PAGO,
                TARGET.D_OBSERVACION = SOURCE.D_OBSERVACION,
                TARGET.F_COMP_ING_MERC = SOURCE.F_COMP_ING_MERC,
                TARGET.C_COMP_ING_MERC = SOURCE.C_COMP_ING_MERC,
                TARGET.U_PREFIJO_COMP_ING_MERC = SOURCE.U_PREFIJO_COMP_ING_MERC,
                TARGET.U_SUFIJO_COMP_ING_MERC = SOURCE.U_SUFIJO_COMP_ING_MERC,
                TARGET.D_OBSERVACION_ING_MERC = SOURCE.D_OBSERVACION_ING_MERC,
                TARGET.C_TIPO_ENTREGA_MERCADERIA = SOURCE.C_TIPO_ENTREGA_MERCADERIA,
                TARGET.C_USUARIO_MODIFICO = SOURCE.C_USUARIO_MODIFICO,
                TARGET.C_TERMINAL_MODIFICO = SOURCE.C_TERMINAL_MODIFICO,
                TARGET.F_MODIFICO = SOURCE.F_MODIFICO,
                TARGET.M_OC_ELECTRONICA = SOURCE.M_OC_ELECTRONICA,
                TARGET.C_SITUAC_OC_ELECTRONICA = SOURCE.C_SITUAC_OC_ELECTRONICA,
                TARGET.F_SITUAC_OC_ELECTRONICA = SOURCE.F_SITUAC_OC_ELECTRONICA,
                TARGET.M_ENVIADO = SOURCE.M_ENVIADO,
                TARGET.M_ESP = SOURCE.M_ESP,
                TARGET.C_TIPO_PROVEEDOR_EDI = SOURCE.C_TIPO_PROVEEDOR_EDI,
                TARGET.FUENTE_ORIGEN = SOURCE.FUENTE_ORIGEN,
                TARGET.FECHA_EXTRACCION = SOURCE.FECHA_EXTRACCION,
                TARGET.CDC_LSN = SOURCE.CDC_LSN,
                TARGET.ESTADO_SINCRONIZACION = SOURCE.ESTADO_SINCRONIZACION

        WHEN NOT MATCHED THEN
            INSERT (C_OC, U_PREFIJO_OC, U_SUFIJO_OC, U_PREFIJO_LOTE, U_LOTE, M_OC_MADRE, M_OC_PARA_TRANSFERENCIA, M_OC_PAGOANT, U_DIAS_LIMITE_ENTREGA, C_PROVEEDOR, C_SUCU_COMPRA, C_SUCU_DESTINO, 
					C_SUCU_DESTINO_ALT, C_SITUAC, F_SITUAC, F_ALTA_SIST, F_EMISION, F_ENTREGA, I_NETO_OC, I_IVA_OC, I_IMP_INTERNO_OC, I_TOTAL_OC, C_COMPRADOR, C_USUARIO_OPERADOR, C_TERMINAL_OPERADOR, 
					C_USUARIO_CUMPLIO, C_TIPO, C_PLAZO_ENTREGA1, C_PLAZO_ENTREGA2, C_PLAZO_ENTREGA3, C_PLAZO_ENTREGA4, C_PLAZO_ENTREGA5, C_PLAZO_ENTREGA6, D_COND_PAGO, D_OBSERVACION, F_COMP_ING_MERC, 
					C_COMP_ING_MERC, U_PREFIJO_COMP_ING_MERC, U_SUFIJO_COMP_ING_MERC, D_OBSERVACION_ING_MERC, C_TIPO_ENTREGA_MERCADERIA, C_USUARIO_MODIFICO, C_TERMINAL_MODIFICO, F_MODIFICO, M_OC_ELECTRONICA, 
					C_SITUAC_OC_ELECTRONICA, F_SITUAC_OC_ELECTRONICA, M_ENVIADO, M_ESP, C_TIPO_PROVEEDOR_EDI, FUENTE_ORIGEN, FECHA_EXTRACCION, CDC_LSN, ESTADO_SINCRONIZACION)
            VALUES (SOURCE.C_OC, SOURCE.U_PREFIJO_OC, SOURCE.U_SUFIJO_OC, SOURCE.U_PREFIJO_LOTE, SOURCE.U_LOTE, SOURCE.M_OC_MADRE, SOURCE.M_OC_PARA_TRANSFERENCIA, SOURCE.M_OC_PAGOANT, SOURCE.U_DIAS_LIMITE_ENTREGA, 
					SOURCE.C_PROVEEDOR, SOURCE.C_SUCU_COMPRA, SOURCE.C_SUCU_DESTINO, SOURCE.C_SUCU_DESTINO_ALT, SOURCE.C_SITUAC, SOURCE.F_SITUAC, SOURCE.F_ALTA_SIST, SOURCE.F_EMISION, SOURCE.F_ENTREGA, 
					SOURCE.I_NETO_OC, SOURCE.I_IVA_OC, SOURCE.I_IMP_INTERNO_OC, SOURCE.I_TOTAL_OC, SOURCE.C_COMPRADOR, SOURCE.C_USUARIO_OPERADOR, SOURCE.C_TERMINAL_OPERADOR, SOURCE.C_USUARIO_CUMPLIO, SOURCE.C_TIPO, 
					SOURCE.C_PLAZO_ENTREGA1, SOURCE.C_PLAZO_ENTREGA2, SOURCE.C_PLAZO_ENTREGA3, SOURCE.C_PLAZO_ENTREGA4, SOURCE.C_PLAZO_ENTREGA5, SOURCE.C_PLAZO_ENTREGA6, SOURCE.D_COND_PAGO, SOURCE.D_OBSERVACION, 
					SOURCE.F_COMP_ING_MERC, SOURCE.C_COMP_ING_MERC, SOURCE.U_PREFIJO_COMP_ING_MERC, SOURCE.U_SUFIJO_COMP_ING_MERC, SOURCE.D_OBSERVACION_ING_MERC, SOURCE.C_TIPO_ENTREGA_MERCADERIA, 
					SOURCE.C_USUARIO_MODIFICO, SOURCE.C_TERMINAL_MODIFICO, SOURCE.F_MODIFICO, SOURCE.M_OC_ELECTRONICA, SOURCE.C_SITUAC_OC_ELECTRONICA, SOURCE.F_SITUAC_OC_ELECTRONICA, SOURCE.M_ENVIADO, 
					SOURCE.M_ESP, SOURCE.C_TIPO_PROVEEDOR_EDI, SOURCE.FUENTE_ORIGEN, SOURCE.FECHA_EXTRACCION, SOURCE.CDC_LSN, SOURCE.ESTADO_SINCRONIZACION);

        SET @total = @@ROWCOUNT;
        SET @mensaje = 'MERGE finalizado correctamente';
    END TRY
    BEGIN CATCH
        SET @mensaje = ERROR_MESSAGE();

		IF XACT_STATE() <> 0
            ROLLBACK;
		
        INSERT INTO repl.LOGS_T080_OC_CABE_SYNC (
            fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
        ) VALUES (GETDATE(), 'ERROR', @mensaje, 0, DATEDIFF(SECOND, @inicio, GETDATE()));
        THROW;
    END CATCH

	BEGIN TRY
		INSERT INTO repl.LOGS_T080_OC_CABE_SYNC (
			fecha_ejecucion, estado, mensaje, registros_afectados, duracion_segundos
		) VALUES (@inicio, 'OK', @mensaje, @total, DATEDIFF(SECOND, @inicio, GETDATE()));
	END TRY
	BEGIN CATCH
    END CATCH
END;
GO


