USE [data-sync]
GO

UPDATE T
SET T.[Q_VENTA_DIARIA] = [Q_VENTA_DIARIA_NORMAL],
	 T.[Q_VENTA_MENSUAL] = (M.[Q_VENTA_30_DIAS] + M.[Q_VENTA_15_DIAS]),
    T.[Q_DIAS_STOCK] = M.[Q_DIAS_STOCK],
    T.[Q_DIAS_ENTREGA_PROVEEDOR] = M.[Q_DIAS_ENTREGA_PROVEEDOR]
FROM [dbo].[T_OC_DETALLE] T
INNER JOIN [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_REPOSICION] M
    ON T.[C_SUCU_COMPRA] = M.[C_SUCU_EMPR]
    AND T.[C_ARTICULO] = M.[C_ARTICULO];      
