SELECT [C_SUCU_EMPR]
      ,[C_ARTICULO]
      ,[Q_VENTA_30_DIAS]
      ,[Q_VENTA_15_DIAS]
      ,[Q_VENTA_DOMINGO]
      ,[Q_VENTA_ESPECIAL_30_DIAS]
      ,[Q_VENTA_ESPECIAL_15_DIAS]
      ,[Q_DIAS_CON_STOCK]
      ,[Q_REPONER]
      ,[Q_REPONER_INCLUIDO_SOBRE_STOCK]
      ,[M_SEMAFORO_INDIVIDUAL]
      ,[M_SEMAFORO_GLOBAL]
      ,[Q_VENTA_DIARIA_NORMAL]
      ,[Q_DIAS_STOCK]
      ,[Q_DIAS_SOBRE_STOCK]
      ,[Q_DIAS_ENTREGA_PROVEEDOR]
  FROM [DIARCOP001].[DiarcoP].[dbo].[T710_ESTADIS_REPOSICION]
  --WHERE [C_SUCU_EMPR] = 38 AND
  --    [C_ARTICULO]= 29636
GO


